import { sql } from 'drizzle-orm';
import { boolean, check, date, index, integer, jsonb, pgTable, primaryKey, text, timestamp, unique, uniqueIndex, uuid, foreignKey } from 'drizzle-orm/pg-core';

export const tenants = pgTable('tenants', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  active: boolean('active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [check('tenants_name_not_empty', sql`length(trim(${t.name})) > 0`), unique('tenants_id_unique').on(t.id)]);

export const patients = pgTable('patients', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id), fullName: text('full_name').notNull(),
  emailCiphertext: text('email_ciphertext'), emailNonce: text('email_nonce'), emailSearchHash: text('email_search_hash'), emailSearchKeyVersion: integer('email_search_key_version'), emailKeyVersion: integer('email_key_version'),
  phoneCiphertext: text('phone_ciphertext'), phoneNonce: text('phone_nonce'), phoneSearchHash: text('phone_search_hash'), phoneSearchKeyVersion: integer('phone_search_key_version'), phoneKeyVersion: integer('phone_key_version'),
  cpfCiphertext: text('cpf_ciphertext'), cpfNonce: text('cpf_nonce'), cpfSearchHash: text('cpf_search_hash'), cpfSearchKeyVersion: integer('cpf_search_key_version'), cpfKeyVersion: integer('cpf_key_version'),
  notesCiphertext: text('notes_ciphertext'), notesNonce: text('notes_nonce'), notesKeyVersion: integer('notes_key_version'), deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'date' }),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [unique('patients_tenant_id_unique').on(t.tenantId, t.id), index('patients_tenant_full_name_trgm').using('gin', t.fullName), index('patients_tenant_id_idx').on(t.tenantId), uniqueIndex('patients_active_email_unique').on(t.tenantId, t.emailSearchHash).where(sql`${t.deletedAt} is null`), uniqueIndex('patients_active_phone_unique').on(t.tenantId, t.phoneSearchHash).where(sql`${t.deletedAt} is null`), uniqueIndex('patients_active_cpf_unique').on(t.tenantId, t.cpfSearchHash).where(sql`${t.deletedAt} is null`), check('patients_full_name_not_empty', sql`length(trim(${t.fullName})) >= 2`)]);

export const patientPendingOperations = pgTable('patient_pending_operations', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id), patientId: uuid('patient_id').notNull(), kind: text('kind').notNull(), resolvedAt: timestamp('resolved_at', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.patientId], foreignColumns: [patients.tenantId, patients.id], name: 'patient_pending_operations_tenant_patient_fk' }), index('patient_pending_operations_patient_idx').on(t.tenantId, t.patientId), check('patient_pending_operations_kind_not_empty', sql`length(trim(${t.kind})) > 0`)]);

const catalogTimestamps = { createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow() };

export const procedures = pgTable('procedures', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), name: text('name').notNull(), description: text('description'), baseSessions: integer('base_sessions'), durationMinutes: integer('duration_minutes').notNull().default(60), standalone: boolean('standalone').notNull().default(true), priceCents: integer('price_cents').notNull().default(0), sessionSchema: jsonb('session_schema').notNull(), active: boolean('active').notNull().default(true), requireNewAnamnesis: boolean('require_new_anamnesis').notNull().default(false), currentVersion: integer('current_version').notNull().default(1), ...catalogTimestamps,
}, (t) => [foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id], name: 'procedures_tenant_fk' }), unique('procedures_tenant_id_unique').on(t.tenantId, t.id), index('procedures_tenant_active_idx').on(t.tenantId, t.active), check('procedures_name_not_empty', sql`length(trim(${t.name})) >= 2`), check('procedures_duration_positive', sql`${t.durationMinutes} between 1 and 1440`), check('procedures_price_nonnegative', sql`${t.priceCents} >= 0`), check('procedures_base_sessions_positive', sql`${t.baseSessions} is null or ${t.baseSessions} >= 1`)]);

export const procedureVersions = pgTable('procedure_versions', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), procedureId: uuid('procedure_id').notNull(), version: integer('version').notNull(), sessionSchema: jsonb('session_schema').notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.procedureId], foreignColumns: [procedures.tenantId, procedures.id], name: 'procedure_versions_tenant_procedure_fk' }), unique('procedure_versions_tenant_procedure_version_unique').on(t.tenantId, t.procedureId, t.version), index('procedure_versions_lookup_idx').on(t.tenantId, t.procedureId)]);

export const anamneses = pgTable('anamneses', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), title: text('title').notNull(), active: boolean('active').notNull().default(true), requiredByDefault: boolean('required_by_default').notNull().default(true), validityMonths: integer('validity_months').notNull().default(12), currentVersion: integer('current_version').notNull().default(1), ...catalogTimestamps,
}, (t) => [foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id], name: 'anamneses_tenant_fk' }), unique('anamneses_tenant_id_unique').on(t.tenantId, t.id), check('anamneses_title_not_empty', sql`length(trim(${t.title})) >= 2`), check('anamneses_validity_positive', sql`${t.validityMonths} >= 1`)]);

export const anamnesisVersions = pgTable('anamnesis_versions', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), anamnesisId: uuid('anamnesis_id').notNull(), version: integer('version').notNull(), schema: jsonb('schema').notNull(), origin: text('origin').notNull().default('created'), restoredFromVersion: integer('restored_from_version'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.anamnesisId], foreignColumns: [anamneses.tenantId, anamneses.id], name: 'anamnesis_versions_tenant_anamnesis_fk' }), unique('anamnesis_versions_tenant_parent_version_unique').on(t.tenantId, t.anamnesisId, t.version), check('anamnesis_versions_origin_valid', sql`${t.origin} in ('created', 'edited', 'restored')`), check('anamnesis_versions_restore_valid', sql`${t.origin} <> 'restored' or ${t.restoredFromVersion} is not null`)]);

export const anamnesisProcedures = pgTable('anamnesis_procedures', {
  tenantId: uuid('tenant_id').notNull(), anamnesisId: uuid('anamnesis_id').notNull(), procedureId: uuid('procedure_id').notNull(), required: boolean('required').notNull().default(true),
}, (t) => [primaryKey({ columns: [t.tenantId, t.anamnesisId, t.procedureId] }), foreignKey({ columns: [t.tenantId, t.anamnesisId], foreignColumns: [anamneses.tenantId, anamneses.id], name: 'anamnesis_procedures_tenant_anamnesis_fk' }), foreignKey({ columns: [t.tenantId, t.procedureId], foreignColumns: [procedures.tenantId, procedures.id], name: 'anamnesis_procedures_tenant_procedure_fk' })]);

export const combos = pgTable('combos', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), name: text('name').notNull(), description: text('description'), priceCents: integer('price_cents').notNull(), promotionalPriceCents: integer('promotional_price_cents'), validFrom: timestamp('valid_from', { withTimezone: true, mode: 'date' }), validUntil: timestamp('valid_until', { withTimezone: true, mode: 'date' }), active: boolean('active').notNull().default(true), requireNewAnamnesis: boolean('require_new_anamnesis').notNull().default(false), ...catalogTimestamps,
}, (t) => [foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id], name: 'combos_tenant_fk' }), unique('combos_tenant_id_unique').on(t.tenantId, t.id), check('combos_name_not_empty', sql`length(trim(${t.name})) >= 2`), check('combos_prices_valid', sql`${t.priceCents} >= 0 and (${t.promotionalPriceCents} is null or (${t.promotionalPriceCents} >= 0 and ${t.promotionalPriceCents} <= ${t.priceCents}))`), check('combos_validity_order', sql`${t.validUntil} is null or ${t.validFrom} is null or ${t.validUntil} >= ${t.validFrom}`)]);

export const comboItems = pgTable('combo_items', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), comboId: uuid('combo_id').notNull(), procedureId: uuid('procedure_id').notNull(), sessions: integer('sessions').notNull(), priceOverrideCents: integer('price_override_cents'),
}, (t) => [foreignKey({ columns: [t.tenantId, t.comboId], foreignColumns: [combos.tenantId, combos.id], name: 'combo_items_tenant_combo_fk' }), foreignKey({ columns: [t.tenantId, t.procedureId], foreignColumns: [procedures.tenantId, procedures.id], name: 'combo_items_tenant_procedure_fk' }), unique('combo_items_tenant_combo_procedure_unique').on(t.tenantId, t.comboId, t.procedureId), check('combo_items_sessions_positive', sql`${t.sessions} >= 1`), check('combo_items_price_nonnegative', sql`${t.priceOverrideCents} is null or ${t.priceOverrideCents} >= 0`)]);

export const contracts = pgTable('contracts', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), title: text('title').notNull(), kind: text('kind').notNull(), procedureId: uuid('procedure_id'), comboId: uuid('combo_id'), active: boolean('active').notNull().default(true), currentVersion: integer('current_version').notNull().default(1), ...catalogTimestamps,
}, (t) => [foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id], name: 'contracts_tenant_fk' }), foreignKey({ columns: [t.tenantId, t.procedureId], foreignColumns: [procedures.tenantId, procedures.id], name: 'contracts_tenant_procedure_fk' }), foreignKey({ columns: [t.tenantId, t.comboId], foreignColumns: [combos.tenantId, combos.id], name: 'contracts_tenant_combo_fk' }), unique('contracts_tenant_id_unique').on(t.tenantId, t.id), check('contracts_kind_valid', sql`${t.kind} in ('standard', 'procedure', 'combo')`), check('contracts_target_valid', sql`(${t.kind} = 'standard' and ${t.procedureId} is null and ${t.comboId} is null) or (${t.kind} = 'procedure' and ${t.procedureId} is not null and ${t.comboId} is null) or (${t.kind} = 'combo' and ${t.comboId} is not null and ${t.procedureId} is null)`)]);

export const contractVersions = pgTable('contract_versions', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), contractId: uuid('contract_id').notNull(), version: integer('version').notNull(), content: text('content'), sourceObjectKey: text('source_object_key'), renderedPdfObjectKey: text('rendered_pdf_object_key'), renderedPdfHash: text('rendered_pdf_hash'), renderedPdfSize: integer('rendered_pdf_size'), renderedPdfContentType: text('rendered_pdf_content_type'), origin: text('origin').notNull().default('created'), restoredFromVersion: integer('restored_from_version'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.contractId], foreignColumns: [contracts.tenantId, contracts.id], name: 'contract_versions_tenant_contract_fk' }), unique('contract_versions_tenant_parent_version_unique').on(t.tenantId, t.contractId, t.version), check('contract_versions_origin_valid', sql`${t.origin} in ('created', 'edited', 'restored')`), check('contract_versions_content_or_object', sql`${t.content} is not null or ${t.sourceObjectKey} is not null`), check('contract_versions_rendered_pdf_metadata_valid', sql`(${t.renderedPdfObjectKey} is null and ${t.renderedPdfHash} is null and ${t.renderedPdfSize} is null and ${t.renderedPdfContentType} is null) or (${t.renderedPdfObjectKey} is not null and ${t.renderedPdfHash} ~ '^[0-9a-fA-F]{64}$' and ${t.renderedPdfSize} > 0 and ${t.renderedPdfContentType} = 'application/pdf')`)]);

export const plans = pgTable('plans', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), name: text('name').notNull(), description: text('description'), active: boolean('active').notNull().default(true), currentVersion: integer('current_version').notNull().default(1), ...catalogTimestamps,
}, (t) => [foreignKey({ columns: [t.tenantId], foreignColumns: [tenants.id], name: 'plans_tenant_fk' }), unique('plans_tenant_id_unique').on(t.tenantId, t.id), check('plans_name_not_empty', sql`length(trim(${t.name})) >= 2`)]);

export const planVersions = pgTable('plan_versions', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), planId: uuid('plan_id').notNull(), version: integer('version').notNull(), priceCents: integer('price_cents').notNull(), durationDays: integer('duration_days'), validityDays: integer('validity_days'), requireNewAnamnesis: boolean('require_new_anamnesis').notNull().default(false), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.planId], foreignColumns: [plans.tenantId, plans.id], name: 'plan_versions_tenant_plan_fk' }), unique('plan_versions_tenant_id_unique').on(t.tenantId, t.id), unique('plan_versions_tenant_plan_id_unique').on(t.tenantId, t.planId, t.id), unique('plan_versions_tenant_parent_version_unique').on(t.tenantId, t.planId, t.version), check('plan_versions_price_nonnegative', sql`${t.priceCents} >= 0`), check('plan_versions_duration_positive', sql`${t.durationDays} is null or ${t.durationDays} >= 1`), check('plan_versions_validity_positive', sql`${t.validityDays} is null or ${t.validityDays} >= 1`)]);

export const planVersionItems = pgTable('plan_version_items', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), planVersionId: uuid('plan_version_id').notNull(), procedureId: uuid('procedure_id').notNull(), sessions: integer('sessions').notNull(), procedureName: text('procedure_name').notNull(), durationMinutes: integer('duration_minutes').notNull(), priceCents: integer('price_cents').notNull(), sessionSchema: jsonb('session_schema').notNull(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.planVersionId], foreignColumns: [planVersions.tenantId, planVersions.id], name: 'plan_version_items_tenant_version_fk' }), foreignKey({ columns: [t.tenantId, t.procedureId], foreignColumns: [procedures.tenantId, procedures.id], name: 'plan_version_items_tenant_procedure_fk' }), check('plan_version_items_sessions_positive', sql`${t.sessions} >= 1`), check('plan_version_items_duration_positive', sql`${t.durationMinutes} >= 1`), check('plan_version_items_price_nonnegative', sql`${t.priceCents} >= 0`)]);

export const planVersionContracts = pgTable('plan_version_contracts', {
  tenantId: uuid('tenant_id').notNull(), planVersionId: uuid('plan_version_id').notNull(), contractId: uuid('contract_id').notNull(), contractVersion: integer('contract_version').notNull(), title: text('title').notNull(), sourceObjectKey: text('source_object_key'),
}, (t) => [primaryKey({ columns: [t.tenantId, t.planVersionId, t.contractId] }), foreignKey({ columns: [t.tenantId, t.planVersionId], foreignColumns: [planVersions.tenantId, planVersions.id], name: 'plan_version_contracts_tenant_version_fk' }), foreignKey({ columns: [t.tenantId, t.contractId], foreignColumns: [contracts.tenantId, contracts.id], name: 'plan_version_contracts_tenant_contract_fk' }), foreignKey({ columns: [t.tenantId, t.contractId, t.contractVersion], foreignColumns: [contractVersions.tenantId, contractVersions.contractId, contractVersions.version], name: 'plan_version_contracts_tenant_contract_version_fk' }), check('plan_version_contracts_version_positive', sql`${t.contractVersion} >= 1`)]);

export const contractVersionPdfUploadIntents = pgTable('contract_version_pdf_upload_intents', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), contractId: uuid('contract_id').notNull(), contractVersion: integer('contract_version').notNull(), objectKey: text('object_key').notNull(), contentHash: text('content_hash').notNull(), contentSize: integer('content_size').notNull(), contentType: text('content_type').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(), consumedAt: timestamp('consumed_at', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.contractId, t.contractVersion], foreignColumns: [contractVersions.tenantId, contractVersions.contractId, contractVersions.version], name: 'contract_version_pdf_upload_intents_version_fk' }), unique('contract_version_pdf_upload_intents_tenant_id_unique').on(t.tenantId, t.id), unique('contract_version_pdf_upload_intents_tenant_object_key_unique').on(t.tenantId, t.objectKey), check('contract_version_pdf_upload_intents_object_key_opaque', sql`${t.objectKey} !~ '[/:]'`), check('contract_version_pdf_upload_intents_hash_valid', sql`${t.contentHash} ~ '^[0-9a-fA-F]{64}$'`), check('contract_version_pdf_upload_intents_size_positive', sql`${t.contentSize} > 0`), check('contract_version_pdf_upload_intents_type_valid', sql`${t.contentType} = 'application/pdf'`)]);

export const tenantDefaults = { id: '00000000-0000-0000-0000-000000000001', name: 'Clínicare' } as const;
export type Tenant = typeof tenants.$inferSelect; export type NewTenant = typeof tenants.$inferInsert;
export type RelationalPatient = typeof patients.$inferSelect; export type NewRelationalPatient = typeof patients.$inferInsert;
export type RelationalProcedure = typeof procedures.$inferSelect; export type NewRelationalProcedure = typeof procedures.$inferInsert;
export type RelationalProcedureVersion = typeof procedureVersions.$inferSelect;
export type RelationalAnamnesis = typeof anamneses.$inferSelect; export type RelationalAnamnesisVersion = typeof anamnesisVersions.$inferSelect;
export type RelationalCombo = typeof combos.$inferSelect; export type RelationalComboItem = typeof comboItems.$inferSelect;
export type RelationalContract = typeof contracts.$inferSelect; export type RelationalContractVersion = typeof contractVersions.$inferSelect; export type RelationalAppliedDocument = typeof appliedDocuments.$inferSelect; export type RelationalAppliedDocumentRevision = typeof appliedDocumentRevisions.$inferSelect;
export const followups = pgTable('followups', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: uuid('tenant_id').notNull(),
  patientId: uuid('patient_id').notNull(),
  offerType: text('offer_type').notNull(),
  offerId: uuid('offer_id').notNull(),
  comboId: uuid('combo_id'),
  planId: uuid('plan_id'),
  planVersionId: uuid('plan_version_id'),
  status: text('status').notNull().default('active'),
  offerNameSnapshot: text('offer_name_snapshot').notNull(),
  priceCents: integer('price_cents').notNull(),
  validUntil: timestamp('valid_until', { withTimezone: true, mode: 'date' }),
  cancellationReason: text('cancellation_reason'),
  completedAt: timestamp('completed_at', { withTimezone: true, mode: 'date' }),
  cancelledAt: timestamp('cancelled_at', { withTimezone: true, mode: 'date' }),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  foreignKey({ columns: [t.tenantId, t.patientId], foreignColumns: [patients.tenantId, patients.id], name: 'followups_tenant_patient_fk' }),
  foreignKey({ columns: [t.tenantId, t.comboId], foreignColumns: [combos.tenantId, combos.id], name: 'followups_tenant_combo_fk' }),
  foreignKey({ columns: [t.tenantId, t.planId], foreignColumns: [plans.tenantId, plans.id], name: 'followups_tenant_plan_fk' }),
  foreignKey({ columns: [t.tenantId, t.planId, t.planVersionId], foreignColumns: [planVersions.tenantId, planVersions.planId, planVersions.id], name: 'followups_tenant_plan_version_fk' }),
  unique('followups_tenant_id_unique').on(t.tenantId, t.id),
  unique('followups_tenant_id_patient_unique').on(t.tenantId, t.id, t.patientId),
  uniqueIndex('followups_live_offer_unique').on(t.tenantId, t.patientId, t.offerType, t.offerId).where(sql`${t.status} not in ('completed', 'cancelled')`),
  index('followups_patient_created_idx').on(t.tenantId, t.patientId, t.createdAt),
  check('followups_offer_type_valid', sql`${t.offerType} in ('procedure', 'combo', 'plan')`),
  check('followups_offer_target_valid', sql`(${t.offerType} = 'procedure' and ${t.comboId} is null and ${t.planId} is null and ${t.planVersionId} is null) or (${t.offerType} = 'combo' and ${t.comboId} = ${t.offerId} and ${t.planId} is null and ${t.planVersionId} is null) or (${t.offerType} = 'plan' and ${t.planId} = ${t.offerId} and ${t.comboId} is null and ${t.planVersionId} is not null)`),
  check('followups_status_valid', sql`${t.status} in ('idle', 'active', 'completed', 'cancelled')`),
  check('followups_price_nonnegative', sql`${t.priceCents} >= 0`),
  check('followups_cancelled_state_valid', sql`(${t.status} = 'cancelled' and ${t.cancelledAt} is not null and ${t.completedAt} is null and ${t.cancellationReason} is not null and length(trim(${t.cancellationReason})) > 0) or (${t.status} <> 'cancelled' and ${t.cancelledAt} is null and ${t.cancellationReason} is null)`),
  check('followups_completed_state_valid', sql`(${t.status} = 'completed' and ${t.completedAt} is not null and ${t.cancelledAt} is null and ${t.cancellationReason} is null) or (${t.status} <> 'completed' and ${t.completedAt} is null)`),
]);

export const followupItems = pgTable('followup_items', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), followupId: uuid('followup_id').notNull(), procedureId: uuid('procedure_id').notNull(), procedureName: text('procedure_name').notNull(), sessionsTotal: integer('sessions_total').notNull(), sessionsPerformed: integer('sessions_performed').notNull().default(0), durationMinutes: integer('duration_minutes').notNull(), priceCents: integer('price_cents').notNull(), sessionSchema: jsonb('session_schema').notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.followupId], foreignColumns: [followups.tenantId, followups.id], name: 'followup_items_tenant_followup_fk' }), foreignKey({ columns: [t.tenantId, t.procedureId], foreignColumns: [procedures.tenantId, procedures.id], name: 'followup_items_tenant_procedure_fk' }), unique('followup_items_tenant_id_unique').on(t.tenantId, t.id), unique('followup_items_tenant_followup_id_unique').on(t.tenantId, t.followupId, t.id), check('followup_items_sessions_positive', sql`${t.sessionsTotal} >= 1`), check('followup_items_performed_valid', sql`${t.sessionsPerformed} between 0 and ${t.sessionsTotal}`), check('followup_items_duration_positive', sql`${t.durationMinutes} >= 1`), check('followup_items_price_nonnegative', sql`${t.priceCents} >= 0`)]);

// Immutable source snapshots are separate from mutable operational counters.
export const followupSnapshots = pgTable('followup_snapshots', {
  id: uuid('id').defaultRandom(), tenantId: uuid('tenant_id').notNull(), followupId: uuid('followup_id').notNull(), kind: text('kind').notNull(), sourceVersion: integer('source_version'), payload: jsonb('payload').notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.followupId], foreignColumns: [followups.tenantId, followups.id], name: 'followup_snapshots_tenant_followup_fk' }), primaryKey({ columns: [t.tenantId, t.followupId, t.kind] }), check('followup_snapshots_kind_valid', sql`${t.kind} in ('combo', 'plan')`)]);

export const followupContracts = pgTable('followup_contracts', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), followupId: uuid('followup_id').notNull(), contractId: uuid('contract_id').notNull(), contractVersion: integer('contract_version').notNull(), titleSnapshot: text('title_snapshot').notNull(), contentCiphertext: text('content_ciphertext'), contentNonce: text('content_nonce'), contentKeyVersion: integer('content_key_version'), sourceObjectKey: text('source_object_key'), renderedPdfObjectKey: text('rendered_pdf_object_key'), renderedPdfHash: text('rendered_pdf_hash'), renderedPdfSize: integer('rendered_pdf_size'), renderedPdfContentType: text('rendered_pdf_content_type'), required: boolean('required').notNull().default(true), patientSignedAt: timestamp('patient_signed_at', { withTimezone: true, mode: 'date' }), professionalSignedAt: timestamp('professional_signed_at', { withTimezone: true, mode: 'date' }), status: text('status').notNull().default('pending'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.followupId], foreignColumns: [followups.tenantId, followups.id], name: 'followup_contracts_tenant_followup_fk' }), foreignKey({ columns: [t.tenantId, t.contractId], foreignColumns: [contracts.tenantId, contracts.id], name: 'followup_contracts_tenant_contract_fk' }), foreignKey({ columns: [t.tenantId, t.contractId, t.contractVersion], foreignColumns: [contractVersions.tenantId, contractVersions.contractId, contractVersions.version], name: 'followup_contracts_tenant_contract_version_fk' }), unique('followup_contracts_tenant_id_unique').on(t.tenantId, t.id), check('followup_contracts_version_positive', sql`${t.contractVersion} >= 1`), check('followup_contracts_status_valid', sql`${t.status} in ('pending', 'signed', 'cancelled')`), check('followup_contracts_content_protected', sql`(${t.contentCiphertext} is null and ${t.contentNonce} is null and ${t.contentKeyVersion} is null) or (${t.contentCiphertext} is not null and ${t.contentNonce} is not null and ${t.contentKeyVersion} is not null)`), check('followup_contracts_rendered_pdf_valid', sql`(${t.renderedPdfObjectKey} is null and ${t.renderedPdfHash} is null and ${t.renderedPdfSize} is null and ${t.renderedPdfContentType} is null) or (${t.renderedPdfObjectKey} is not null and ${t.renderedPdfHash} ~ '^[0-9a-fA-F]{64}$' and ${t.renderedPdfSize} > 0 and ${t.renderedPdfContentType} = 'application/pdf')`)]) ;

export const appliedDocuments: any = pgTable('applied_documents', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), followupContractId: uuid('followup_contract_id').notNull(), originalObjectKey: text('original_object_key'), originalHash: text('original_hash'), originalSize: integer('original_size'), currentRevisionId: uuid('current_revision_id'), legacyUnsupported: boolean('legacy_unsupported').notNull().default(false), objectKey: text('object_key'), contentHash: text('content_hash'), contentType: text('content_type'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.followupContractId], foreignColumns: [followupContracts.tenantId, followupContracts.id], name: 'applied_documents_tenant_contract_fk' }), foreignKey({ columns: [t.tenantId, t.id, t.currentRevisionId], foreignColumns: [appliedDocumentRevisions.tenantId, appliedDocumentRevisions.documentId, appliedDocumentRevisions.id], name: 'applied_documents_current_revision_fk' }), unique('applied_documents_tenant_id_unique').on(t.tenantId, t.id), uniqueIndex('applied_documents_tenant_contract_unique').on(t.tenantId, t.followupContractId).where(sql`${t.legacyUnsupported} = false`), check('applied_documents_original_object_key_opaque', sql`${t.originalObjectKey} is null or ${t.originalObjectKey} !~ '[/:]'`), check('applied_documents_original_hash_valid', sql`${t.originalHash} is null or ${t.originalHash} ~ '^[0-9a-fA-F]{64}$'`), check('applied_documents_original_size_positive', sql`${t.originalSize} is null or ${t.originalSize} > 0`) ]);

export const pdfUploadIntents = pgTable('pdf_upload_intents', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), followupContractId: uuid('followup_contract_id').notNull(), objectKey: text('object_key').notNull(), contentHash: text('content_hash').notNull(), contentSize: integer('content_size').notNull(), contentType: text('content_type').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(), consumedAt: timestamp('consumed_at', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.followupContractId], foreignColumns: [followupContracts.tenantId, followupContracts.id], name: 'pdf_upload_intents_tenant_contract_fk' }), unique('pdf_upload_intents_tenant_id_unique').on(t.tenantId, t.id), unique('pdf_upload_intents_tenant_object_key_unique').on(t.tenantId, t.objectKey), check('pdf_upload_intents_object_key_opaque', sql`${t.objectKey} !~ '[/:]'`), check('pdf_upload_intents_hash_valid', sql`${t.contentHash} ~ '^[0-9a-fA-F]{64}$'`), check('pdf_upload_intents_size_positive', sql`${t.contentSize} > 0`), check('pdf_upload_intents_type_valid', sql`${t.contentType} = 'application/pdf'`)]);

export const appliedDocumentRevisions: any = pgTable('applied_document_revisions', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), documentId: uuid('document_id').notNull(), version: integer('version').notNull(), parentRevisionId: uuid('parent_revision_id'), objectKey: text('object_key').notNull(), contentHash: text('content_hash').notNull(), contentSize: integer('content_size').notNull(), origin: text('origin').notNull().default('initial'), sourceExternalReceiptId: uuid('source_external_receipt_id'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.documentId], foreignColumns: [appliedDocuments.tenantId, appliedDocuments.id], name: 'applied_document_revisions_tenant_document_fk' }), foreignKey({ columns: [t.tenantId, t.documentId, t.parentRevisionId], foreignColumns: [appliedDocumentRevisions.tenantId, appliedDocumentRevisions.documentId, appliedDocumentRevisions.id], name: 'applied_document_revisions_tenant_document_parent_fk' }), unique('applied_document_revisions_tenant_id_unique').on(t.tenantId, t.id), unique('applied_document_revisions_tenant_document_id_unique').on(t.tenantId, t.documentId, t.id), unique('applied_document_revisions_document_version_unique').on(t.tenantId, t.documentId, t.version), uniqueIndex('applied_document_revisions_parent_unique').on(t.tenantId, t.documentId, t.parentRevisionId).where(sql`${t.parentRevisionId} is not null`), check('applied_document_revisions_object_key_opaque', sql`${t.objectKey} !~ '[/:]'`), check('applied_document_revisions_version_positive', sql`${t.version} >= 1`), check('applied_document_revisions_content_hash_valid', sql`${t.contentHash} ~ '^[0-9a-fA-F]{64}$'`), check('applied_document_revisions_content_size_positive', sql`${t.contentSize} > 0`)]);

/** Durable outbox for object-store work that must survive a process crash. */
export const documentCleanupJobs: any = pgTable('document_cleanup_jobs', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id), documentId: uuid('document_id'), objectKeys: jsonb('object_keys').notNull(), status: text('status').notNull().default('pending'), attempts: integer('attempts').notNull().default(0), lastError: text('last_error'), attemptedAt: timestamp('attempted_at', { withTimezone: true, mode: 'date' }), completedAt: timestamp('completed_at', { withTimezone: true, mode: 'date' }), claimToken: text('claim_token'), claimExpiresAt: timestamp('claim_expires_at', { withTimezone: true, mode: 'date' }), reservationExpiresAt: timestamp('reservation_expires_at', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [index('document_cleanup_jobs_status_idx').on(t.tenantId, t.status, t.updatedAt), index('document_cleanup_jobs_document_idx').on(t.tenantId, t.documentId), index('document_cleanup_jobs_claim_idx').on(t.status, t.claimExpiresAt), index('document_cleanup_jobs_reservation_idx').on(t.status, t.reservationExpiresAt), check('document_cleanup_jobs_status_valid', sql`${t.status} in ('reserved', 'pending', 'processing', 'completed', 'failed')`), check('document_cleanup_jobs_attempts_valid', sql`${t.attempts} >= 0`), check('document_cleanup_jobs_object_keys_array', sql`jsonb_typeof(${t.objectKeys}) = 'array'`)]);

export const signatureProcesses = pgTable('signature_processes', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), followupContractId: uuid('followup_contract_id').notNull(), status: text('status').notNull().default('pending'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.followupContractId], foreignColumns: [followupContracts.tenantId, followupContracts.id], name: 'signature_processes_tenant_contract_fk' }), unique('signature_processes_tenant_id_unique').on(t.tenantId, t.id), unique('signature_processes_tenant_contract_unique').on(t.tenantId, t.followupContractId), check('signature_processes_status_valid', sql`${t.status} in ('pending', 'completed', 'cancelled')`)]);
export const signatureParticipants = pgTable('signature_participants', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), processId: uuid('process_id').notNull(), role: text('role').notNull(), status: text('status').notNull().default('pending'), signedAt: timestamp('signed_at', { withTimezone: true, mode: 'date' }), latestRevision: integer('latest_revision').notNull().default(0), identitySnapshot: jsonb('identity_snapshot'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.processId], foreignColumns: [signatureProcesses.tenantId, signatureProcesses.id], name: 'signature_participants_tenant_process_fk' }), unique('signature_participants_role_unique').on(t.tenantId, t.processId, t.role), check('signature_participants_role_valid', sql`${t.role} in ('patient', 'professional')`), check('signature_participants_status_valid', sql`${t.status} in ('pending', 'signed', 'revoked')`), check('signature_participants_state_valid', sql`(${t.status} = 'signed' and ${t.signedAt} is not null) or (${t.status} <> 'signed' and ${t.signedAt} is null)`)]);
export const signatureOperations: any = pgTable('signature_operations', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), participantId: uuid('participant_id').notNull(), documentId: uuid('document_id').notNull(), baseRevisionId: uuid('base_revision_id').notNull(), candidateObjectKey: text('candidate_object_key').notNull(), candidateHash: text('candidate_hash').notNull(), candidateSize: integer('candidate_size').notNull(), method: text('method').notNull().default('local_handwritten'), placement: jsonb('placement').notNull(), idempotencyKey: text('idempotency_key').notNull(), requestHash: text('request_hash').notNull(), signatureImageHash: text('signature_image_hash').notNull(), signatureImageObjectKey: text('signature_image_object_key'), acceptanceText: text('acceptance_text').notNull(), identitySnapshot: jsonb('identity_snapshot'), fingerprint: jsonb('fingerprint'), fingerprintCollectorVersion: text('fingerprint_collector_version'), fingerprintNormalizationVersion: text('fingerprint_normalization_version'), fingerprintDigest: text('fingerprint_digest'), observedIp: text('observed_ip'), evidenceReceivedAt: timestamp('evidence_received_at', { withTimezone: true, mode: 'date' }), status: text('status').notNull().default('prepared'), staleReason: text('stale_reason'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), confirmedAt: timestamp('confirmed_at', { withTimezone: true, mode: 'date' }),
}, (t) => [foreignKey({ columns: [t.tenantId, t.participantId], foreignColumns: [signatureParticipants.tenantId, signatureParticipants.id], name: 'signature_operations_tenant_participant_fk' }), foreignKey({ columns: [t.tenantId, t.documentId], foreignColumns: [appliedDocuments.tenantId, appliedDocuments.id], name: 'signature_operations_tenant_document_fk' }), foreignKey({ columns: [t.tenantId, t.documentId, t.baseRevisionId], foreignColumns: [appliedDocumentRevisions.tenantId, appliedDocumentRevisions.documentId, appliedDocumentRevisions.id], name: 'signature_operations_tenant_base_revision_fk' }), unique('signature_operations_tenant_id_unique').on(t.tenantId, t.id), uniqueIndex('signature_operations_idempotency_unique').on(t.tenantId, t.participantId, t.idempotencyKey), index('signature_operations_document_idx').on(t.tenantId, t.documentId, t.createdAt), uniqueIndex('signature_operations_signature_image_key_unique').on(t.tenantId, t.signatureImageObjectKey), check('signature_operations_method_valid', sql`${t.method} in ('local_handwritten')`), check('signature_operations_status_valid', sql`${t.status} in ('prepared', 'confirmed', 'stale', 'rejected')`), check('signature_operations_hash_valid', sql`${t.candidateHash} is null or ${t.candidateHash} ~ '^[0-9a-fA-F]{64}$'`), check('signature_operations_request_hash_valid', sql`${t.requestHash} ~ '^[0-9a-fA-F]{64}$'`), check('signature_operations_signature_hash_valid', sql`${t.signatureImageHash} ~ '^[0-9a-fA-F]{64}$'`), check('signature_operations_size_positive', sql`${t.candidateSize} is null or ${t.candidateSize} > 0`), check('signature_operations_idempotency_not_empty', sql`length(trim(${t.idempotencyKey})) > 0`), check('signature_operations_candidate_key_opaque', sql`${t.candidateObjectKey} !~ '[/:]'`)]);
export const signatureRevisions: any = pgTable('signature_revisions', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), participantId: uuid('participant_id').notNull(), revision: integer('revision').notNull(), evidenceCiphertext: text('evidence_ciphertext'), evidenceNonce: text('evidence_nonce'), evidenceKeyVersion: integer('evidence_key_version'), operationId: uuid('operation_id'), documentRevisionId: uuid('document_revision_id'), method: text('method'), placement: jsonb('placement'), signatureImageHash: text('signature_image_hash'), externalReceiptId: uuid('external_receipt_id'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.participantId], foreignColumns: [signatureParticipants.tenantId, signatureParticipants.id], name: 'signature_revisions_tenant_participant_fk' }), foreignKey({ columns: [t.tenantId, t.operationId], foreignColumns: [signatureOperations.tenantId, signatureOperations.id], name: 'signature_revisions_tenant_operation_fk' }), foreignKey({ columns: [t.tenantId, t.documentRevisionId], foreignColumns: [appliedDocumentRevisions.tenantId, appliedDocumentRevisions.id], name: 'signature_revisions_tenant_document_revision_fk' }), unique('signature_revisions_number_unique').on(t.tenantId, t.participantId, t.revision), check('signature_revisions_positive', sql`${t.revision} >= 1`)]);
export const signatureExternalAttempts: any = pgTable('signature_external_attempts', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), participantId: uuid('participant_id').notNull(), documentId: uuid('document_id').notNull(), baseRevisionId: uuid('base_revision_id').notNull(), provider: text('provider').notNull().default('govbr'), lifecycleStatus: text('lifecycle_status').notNull().default('reserved'), validationStatus: text('validation_status'), idempotencyKey: text('idempotency_key').notNull(), exportObjectKey: text('export_object_key').notNull(), exportHash: text('export_hash').notNull(), exportSize: integer('export_size').notNull(), exportExpiresAt: timestamp('export_expires_at', { withTimezone: true, mode: 'date' }).notNull(), exportedAt: timestamp('exported_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), importObjectKey: text('import_object_key'), importHash: text('import_hash'), importSize: integer('import_size'), importedAt: timestamp('imported_at', { withTimezone: true, mode: 'date' }), exportFingerprint: jsonb('export_fingerprint'), importFingerprint: jsonb('import_fingerprint'), cancelledAt: timestamp('cancelled_at', { withTimezone: true, mode: 'date' }), completedAt: timestamp('completed_at', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.participantId], foreignColumns: [signatureParticipants.tenantId, signatureParticipants.id], name: 'signature_external_attempts_tenant_participant_fk' }), foreignKey({ columns: [t.tenantId, t.documentId], foreignColumns: [appliedDocuments.tenantId, appliedDocuments.id], name: 'signature_external_attempts_tenant_document_fk' }), foreignKey({ columns: [t.tenantId, t.documentId, t.baseRevisionId], foreignColumns: [appliedDocumentRevisions.tenantId, appliedDocumentRevisions.documentId, appliedDocumentRevisions.id], name: 'signature_external_attempts_tenant_revision_fk' }), unique('signature_external_attempts_tenant_id_unique').on(t.tenantId, t.id),
  uniqueIndex('signature_external_attempts_idempotency_unique').on(t.tenantId, t.participantId, t.idempotencyKey), index('signature_external_attempts_status_idx').on(t.tenantId, t.participantId, t.lifecycleStatus), index('signature_external_attempts_expiry_idx').on(t.tenantId, t.exportExpiresAt)]);
export const signatureExternalReceipts: any = pgTable('signature_external_receipts', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), attemptId: uuid('attempt_id').notNull(), objectKey: text('object_key').notNull(), contentHash: text('content_hash').notNull(), contentSize: integer('content_size').notNull(), receivedAt: timestamp('received_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), validationStatus: text('validation_status').notNull().default('indeterminate'), validationReport: jsonb('validation_report'), signerIdentity: jsonb('signer_identity'), certificateFingerprint: text('certificate_fingerprint'), coveredRevisionIds: jsonb('covered_revision_ids'), detectedSignatureIds: jsonb('detected_signature_ids'), promotedRevisionId: uuid('promoted_revision_id'), rejectedReason: text('rejected_reason'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.attemptId], foreignColumns: [signatureExternalAttempts.tenantId, signatureExternalAttempts.id], name: 'signature_external_receipts_tenant_attempt_fk' }), foreignKey({ columns: [t.tenantId, t.promotedRevisionId], foreignColumns: [appliedDocumentRevisions.tenantId, appliedDocumentRevisions.id], name: 'signature_external_receipts_tenant_revision_fk' }), unique('signature_external_receipts_tenant_id_unique').on(t.tenantId, t.id),
  index('signature_external_receipts_attempt_idx').on(t.tenantId, t.attemptId, t.receivedAt)]);
export const signaturePreviewCandidates: any = pgTable('signature_preview_candidates', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), participantId: uuid('participant_id').notNull(), documentId: uuid('document_id').notNull(), baseRevisionId: uuid('base_revision_id').notNull(), objectKey: text('object_key').notNull(), contentHash: text('content_hash').notNull(), contentSize: integer('content_size').notNull(), signatureImageHash: text('signature_image_hash').notNull(), placement: jsonb('placement').notNull(), idempotencyKey: text('idempotency_key').notNull(), fingerprint: jsonb('fingerprint'), expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(), consumedAt: timestamp('consumed_at', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.participantId], foreignColumns: [signatureParticipants.tenantId, signatureParticipants.id], name: 'signature_preview_candidates_tenant_participant_fk' }), foreignKey({ columns: [t.tenantId, t.documentId], foreignColumns: [appliedDocuments.tenantId, appliedDocuments.id], name: 'signature_preview_candidates_tenant_document_fk' }), foreignKey({ columns: [t.tenantId, t.documentId, t.baseRevisionId], foreignColumns: [appliedDocumentRevisions.tenantId, appliedDocumentRevisions.documentId, appliedDocumentRevisions.id], name: 'signature_preview_candidates_tenant_revision_fk' }), uniqueIndex('signature_preview_candidates_idempotency_unique').on(t.tenantId, t.participantId, t.idempotencyKey), index('signature_preview_candidates_expiry_idx').on(t.expiresAt)]);
export const signatureStorageCleanupJobs: any = pgTable('signature_storage_cleanup_jobs', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), participantId: uuid('participant_id'), objectKey: text('object_key').notNull(), reason: text('reason').notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), completedAt: timestamp('completed_at', { withTimezone: true, mode: 'date' }),
}, (t) => [foreignKey({ columns: [t.tenantId, t.participantId], foreignColumns: [signatureParticipants.tenantId, signatureParticipants.id], name: 'signature_storage_cleanup_jobs_tenant_participant_fk' }), index('signature_storage_cleanup_jobs_pending_idx').on(t.tenantId, t.createdAt)]);
export const signatureEvidence: any = pgTable('signature_evidence', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), participantId: uuid('participant_id').notNull(), documentId: uuid('document_id').notNull(), documentRevisionId: uuid('document_revision_id'), operationId: uuid('operation_id'), externalAttemptId: uuid('external_attempt_id'), eventType: text('event_type').notNull(), collectorVersion: text('collector_version'), normalizationVersion: text('normalization_version'), attributes: jsonb('attributes'), unavailableAttributes: jsonb('unavailable_attributes'), normalizedRepresentation: jsonb('normalized_representation'), digest: text('digest'), observedIp: text('observed_ip'), observedAt: timestamp('observed_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.participantId], foreignColumns: [signatureParticipants.tenantId, signatureParticipants.id], name: 'signature_evidence_tenant_participant_fk' }), foreignKey({ columns: [t.tenantId, t.documentId], foreignColumns: [appliedDocuments.tenantId, appliedDocuments.id], name: 'signature_evidence_tenant_document_fk' }), foreignKey({ columns: [t.tenantId, t.documentRevisionId], foreignColumns: [appliedDocumentRevisions.tenantId, appliedDocumentRevisions.id], name: 'signature_evidence_tenant_revision_fk' }), foreignKey({ columns: [t.tenantId, t.operationId], foreignColumns: [signatureOperations.tenantId, signatureOperations.id], name: 'signature_evidence_tenant_operation_fk' }), foreignKey({ columns: [t.tenantId, t.externalAttemptId], foreignColumns: [signatureExternalAttempts.tenantId, signatureExternalAttempts.id], name: 'signature_evidence_tenant_attempt_fk' }), index('signature_evidence_participant_idx').on(t.tenantId, t.participantId, t.observedAt)]);
export const signatureEvents = pgTable('signature_events', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), participantId: uuid('participant_id').notNull(), revisionId: uuid('revision_id'), type: text('type').notNull(), metadata: jsonb('metadata'), occurredAt: timestamp('occurred_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.participantId], foreignColumns: [signatureParticipants.tenantId, signatureParticipants.id], name: 'signature_events_tenant_participant_fk' }), foreignKey({ columns: [t.tenantId, t.revisionId], foreignColumns: [signatureRevisions.tenantId, signatureRevisions.id], name: 'signature_events_tenant_revision_fk', }), index('signature_events_participant_idx').on(t.tenantId, t.participantId, t.occurredAt)]);
export const signatureTokens = pgTable('signature_tokens', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), participantId: uuid('participant_id').notNull(), tokenHash: text('token_hash').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(), revokedAt: timestamp('revoked_at', { withTimezone: true, mode: 'date' }), phoneVerifiedAt: timestamp('phone_verified_at', { withTimezone: true, mode: 'date' }), phoneVerificationAttempts: integer('phone_verification_attempts').notNull().default(0), phoneLockedUntil: timestamp('phone_locked_until', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.participantId], foreignColumns: [signatureParticipants.tenantId, signatureParticipants.id], name: 'signature_tokens_tenant_participant_fk' }), unique('signature_tokens_hash_unique').on(t.tenantId, t.tokenHash), index('signature_tokens_active_idx').on(t.tenantId, t.participantId, t.expiresAt), check('signature_tokens_hash_not_empty', sql`length(${t.tokenHash}) >= 64`)]);

export const appliedAnamneses = pgTable('applied_anamneses', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), patientId: uuid('patient_id').notNull(), followupId: uuid('followup_id').notNull(), anamnesisId: uuid('anamnesis_id').notNull(), version: integer('version').notNull(), titleSnapshot: text('title_snapshot').notNull(), schemaSnapshot: jsonb('schema_snapshot').notNull(), validityMonths: integer('validity_months'), required: boolean('required').notNull().default(true),
  requestTokenHash: text('request_token_hash'), requestExpiresAt: timestamp('request_expires_at', { withTimezone: true, mode: 'date' }),
  draftCiphertext: text('draft_ciphertext'), draftNonce: text('draft_nonce'), draftKeyVersion: integer('draft_key_version'),
  answersCiphertext: text('answers_ciphertext'), answersNonce: text('answers_nonce'), answersKeyVersion: integer('answers_key_version'),
  submittedAt: timestamp('submitted_at', { withTimezone: true, mode: 'date' }), validUntil: timestamp('valid_until', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.patientId], foreignColumns: [patients.tenantId, patients.id], name: 'applied_anamneses_tenant_patient_fk' }), foreignKey({ columns: [t.tenantId, t.followupId, t.patientId], foreignColumns: [followups.tenantId, followups.id, followups.patientId], name: 'applied_anamneses_tenant_followup_patient_fk' }), foreignKey({ columns: [t.tenantId, t.anamnesisId], foreignColumns: [anamneses.tenantId, anamneses.id], name: 'applied_anamneses_tenant_anamnesis_fk' }), unique('applied_anamneses_tenant_id_unique').on(t.tenantId, t.id), uniqueIndex('applied_anamneses_request_token_unique').on(t.tenantId, t.requestTokenHash).where(sql`${t.requestTokenHash} is not null`), check('applied_anamneses_version_positive', sql`${t.version} >= 1`), check('applied_anamneses_draft_protected', sql`(${t.draftCiphertext} is null and ${t.draftNonce} is null and ${t.draftKeyVersion} is null) or (${t.draftCiphertext} is not null and ${t.draftNonce} is not null and ${t.draftKeyVersion} is not null)`), check('applied_anamneses_answers_protected', sql`(${t.answersCiphertext} is null and ${t.answersNonce} is null and ${t.answersKeyVersion} is null) or (${t.answersCiphertext} is not null and ${t.answersNonce} is not null and ${t.answersKeyVersion} is not null)`)]);

export const appliedAnamnesisNotes = pgTable('applied_anamnesis_notes', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), appliedAnamnesisId: uuid('applied_anamnesis_id').notNull(), contentCiphertext: text('content_ciphertext').notNull(), contentNonce: text('content_nonce').notNull(), contentKeyVersion: integer('content_key_version').notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.appliedAnamnesisId], foreignColumns: [appliedAnamneses.tenantId, appliedAnamneses.id], name: 'applied_anamnesis_notes_tenant_applied_fk' }), index('applied_anamnesis_notes_lookup_idx').on(t.tenantId, t.appliedAnamnesisId, t.createdAt)]);


export const payments = pgTable('payments', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), followupId: uuid('followup_id').notNull(), amountCents: integer('amount_cents').notNull(), method: text('method').notNull(), installments: integer('installments').notNull().default(1), receivedAt: timestamp('received_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), notesCiphertext: text('notes_ciphertext'), notesNonce: text('notes_nonce'), notesKeyVersion: integer('notes_key_version'), idempotencyKey: text('idempotency_key'), deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'date' }), deletionReason: text('deletion_reason'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.followupId], foreignColumns: [followups.tenantId, followups.id], name: 'payments_tenant_followup_fk' }), unique('payments_tenant_id_unique').on(t.tenantId, t.id), uniqueIndex('payments_idempotency_unique').on(t.tenantId, t.idempotencyKey).where(sql`${t.idempotencyKey} is not null`), index('payments_followup_received_idx').on(t.tenantId, t.followupId, t.receivedAt), check('payments_amount_positive', sql`${t.amountCents} > 0`), check('payments_installments_positive', sql`${t.installments} >= 1`), check('payments_method_valid', sql`${t.method} in ('cash', 'pix', 'credit_card')`), check('payments_deleted_reason_valid', sql`(${t.deletedAt} is null and ${t.deletionReason} is null) or (${t.deletedAt} is not null and ${t.deletionReason} is not null and length(trim(${t.deletionReason})) > 0`), check('payments_notes_protected', sql`(${t.notesCiphertext} is null and ${t.notesNonce} is null and ${t.notesKeyVersion} is null) or (${t.notesCiphertext} is not null and ${t.notesNonce} is not null and ${t.notesKeyVersion} is not null)`)]);

// Corrections and refunds are appended as new records; the confirmed source record remains immutable.
export const paymentRelations = pgTable('payment_relations', {
  tenantId: uuid('tenant_id').notNull(), paymentId: uuid('payment_id').notNull(), relatedPaymentId: uuid('related_payment_id').notNull(), relationType: text('relation_type').notNull(), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [primaryKey({ columns: [t.tenantId, t.paymentId, t.relatedPaymentId, t.relationType] }), foreignKey({ columns: [t.tenantId, t.paymentId], foreignColumns: [payments.tenantId, payments.id], name: 'payment_relations_payment_fk' }), foreignKey({ columns: [t.tenantId, t.relatedPaymentId], foreignColumns: [payments.tenantId, payments.id], name: 'payment_relations_related_payment_fk' }), check('payment_relations_type_valid', sql`${t.relationType} in ('adjustment', 'refund')`), check('payment_relations_distinct', sql`${t.paymentId} <> ${t.relatedPaymentId}`)]);

export type RelationalFollowup = typeof followups.$inferSelect; export type RelationalFollowupItem = typeof followupItems.$inferSelect; export type RelationalPayment = typeof payments.$inferSelect; export type RelationalAppliedAnamnesis = typeof appliedAnamneses.$inferSelect; export type RelationalAppliedAnamnesisNote = typeof appliedAnamnesisNotes.$inferSelect;

export const appointments = pgTable('appointments', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), patientId: uuid('patient_id').notNull(),
  startsAt: timestamp('starts_at', { withTimezone: true, mode: 'date' }).notNull(), endsAt: timestamp('ends_at', { withTimezone: true, mode: 'date' }).notNull(),
  status: text('status').notNull().default('planned'), notesCiphertext: text('notes_ciphertext'), notesNonce: text('notes_nonce'), notesKeyVersion: integer('notes_key_version'), deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'date' }),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.patientId], foreignColumns: [patients.tenantId, patients.id], name: 'appointments_tenant_patient_fk' }), unique('appointments_tenant_id_unique').on(t.tenantId, t.id), index('appointments_tenant_status_starts_idx').on(t.tenantId, t.status, t.startsAt), check('appointments_interval_valid', sql`${t.endsAt} > ${t.startsAt}`), check('appointments_status_valid', sql`${t.status} in ('planned','confirmed','rescheduled','cancelled','no_show')`), check('appointments_notes_protected', sql`(${t.notesCiphertext} is null and ${t.notesNonce} is null and ${t.notesKeyVersion} is null) or (${t.notesCiphertext} is not null and ${t.notesNonce} is not null and ${t.notesKeyVersion} is not null)`)]);

export const appointmentItems = pgTable('appointment_items', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), appointmentId: uuid('appointment_id').notNull(), followupId: uuid('followup_id'), followupItemId: uuid('followup_item_id'), procedureId: uuid('procedure_id').notNull(), procedureName: text('procedure_name').notNull(), quantity: integer('quantity').notNull().default(1), minutesEach: integer('minutes_each').notNull(), confirmationStatus: text('confirmation_status').notNull().default('pending'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.appointmentId], foreignColumns: [appointments.tenantId, appointments.id], name: 'appointment_items_tenant_appointment_fk' }), foreignKey({ columns: [t.tenantId, t.followupId], foreignColumns: [followups.tenantId, followups.id], name: 'appointment_items_tenant_followup_fk' }), foreignKey({ columns: [t.tenantId, t.followupId, t.followupItemId], foreignColumns: [followupItems.tenantId, followupItems.followupId, followupItems.id], name: 'appointment_items_tenant_followup_item_pair_fk' }), foreignKey({ columns: [t.tenantId, t.procedureId], foreignColumns: [procedures.tenantId, procedures.id], name: 'appointment_items_tenant_procedure_fk' }), unique('appointment_items_tenant_id_unique').on(t.tenantId, t.id), index('appointment_items_followup_idx').on(t.tenantId, t.followupItemId), check('appointment_items_quantity_positive', sql`${t.quantity} >= 1`), check('appointment_items_minutes_positive', sql`${t.minutesEach} >= 1`), check('appointment_items_confirmation_valid', sql`${t.confirmationStatus} in ('pending','selected','confirmed','deselected','cancelled')`), check('appointment_items_followup_pair_valid', sql`(${t.followupId} is null and ${t.followupItemId} is null) or (${t.followupId} is not null and ${t.followupItemId} is not null)`)]);

export const attendances = pgTable('attendances', {
  id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), patientId: uuid('patient_id').notNull(), followupId: uuid('followup_id'), followupItemId: uuid('followup_item_id'), appointmentId: uuid('appointment_id'), procedureId: uuid('procedure_id').notNull(), procedureName: text('procedure_name').notNull(), performedAt: timestamp('performed_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), durationMinutes: integer('duration_minutes'), dataCiphertext: text('data_ciphertext'), dataNonce: text('data_nonce'), dataKeyVersion: integer('data_key_version'), schemaSnapshot: jsonb('schema_snapshot').notNull(), notesCiphertext: text('notes_ciphertext'), notesNonce: text('notes_nonce'), notesKeyVersion: integer('notes_key_version'), status: text('status').notNull().default('performed'), cancellationReason: text('cancellation_reason'), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.tenantId, t.patientId], foreignColumns: [patients.tenantId, patients.id], name: 'attendances_tenant_patient_fk' }), foreignKey({ columns: [t.tenantId, t.followupId, t.patientId], foreignColumns: [followups.tenantId, followups.id, followups.patientId], name: 'attendances_tenant_followup_patient_fk' }), foreignKey({ columns: [t.tenantId, t.followupId, t.followupItemId], foreignColumns: [followupItems.tenantId, followupItems.followupId, followupItems.id], name: 'attendances_tenant_followup_item_pair_fk' }), foreignKey({ columns: [t.tenantId, t.appointmentId], foreignColumns: [appointments.tenantId, appointments.id], name: 'attendances_tenant_appointment_fk' }), unique('attendances_tenant_id_unique').on(t.tenantId, t.id), index('attendances_followup_item_idx').on(t.tenantId, t.followupItemId, t.status), index('attendances_patient_idx').on(t.tenantId, t.patientId, t.performedAt), check('attendances_duration_valid', sql`${t.durationMinutes} is null or ${t.durationMinutes} between 1 and 1440`), check('attendances_status_valid', sql`${t.status} in ('performed','cancelled')`), check('attendances_cancel_state_valid', sql`(${t.status} = 'cancelled' and ${t.cancellationReason} is not null and length(trim(${t.cancellationReason})) > 0) or (${t.status} = 'performed' and ${t.cancellationReason} is null)`), check('attendances_data_protected', sql`(${t.dataCiphertext} is null and ${t.dataNonce} is null and ${t.dataKeyVersion} is null) or (${t.dataCiphertext} is not null and ${t.dataNonce} is not null and ${t.dataKeyVersion} is not null)`), check('attendances_notes_protected', sql`(${t.notesCiphertext} is null and ${t.notesNonce} is null and ${t.notesKeyVersion} is null) or (${t.notesCiphertext} is not null and ${t.notesNonce} is not null and ${t.notesKeyVersion} is not null)`)]);

export const attendancePhotos = pgTable('attendance_photos', { id: uuid('id').defaultRandom().primaryKey(), tenantId: uuid('tenant_id').notNull(), attendanceId: uuid('attendance_id').notNull(), objectKey: text('object_key').notNull(), contentHash: text('content_hash'), phase: text('phase').notNull(), notesCiphertext: text('notes_ciphertext'), notesNonce: text('notes_nonce'), notesKeyVersion: integer('notes_key_version'), deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow() }, (t) => [foreignKey({ columns: [t.tenantId, t.attendanceId], foreignColumns: [attendances.tenantId, attendances.id], name: 'attendance_photos_tenant_attendance_fk' }), index('attendance_photos_attendance_idx').on(t.tenantId, t.attendanceId, t.createdAt), check('attendance_photos_phase_valid', sql`${t.phase} in ('before','during','after')`), check('attendance_photos_object_key_opaque', sql`${t.objectKey} !~ '[/:]'`), check('attendance_photos_notes_protected', sql`(${t.notesCiphertext} is null and ${t.notesNonce} is null and ${t.notesKeyVersion} is null) or (${t.notesCiphertext} is not null and ${t.notesNonce} is not null and ${t.notesKeyVersion} is not null)`)]);

export type RelationalPlan = typeof plans.$inferSelect; export type RelationalPlanVersion = typeof planVersions.$inferSelect; export type RelationalAppointment = typeof appointments.$inferSelect; export type RelationalAppointmentItem = typeof appointmentItems.$inferSelect; export type RelationalAttendance = typeof attendances.$inferSelect;
