import { useEffect, useMemo, useState } from 'react';
import { Activity, CalendarDays, ChevronDown, ChevronRight, CircleHelp, ClipboardList, FileText, LayoutDashboard, Plus, Search, Settings2, Sparkles, UserRound, UsersRound, WalletCards } from 'lucide-react';
import { SchemaEditor, SchemaForm } from './components/SchemaForm';
import { CalendarView } from './components/CalendarView';
import type { DateSelectArg, EventClickArg } from '@fullcalendar/core';

type Patient = { id: string; fullName: string; phone: string | null; email: string | null; notes: string | null; createdAt: string };
type Procedure = { id: string; name: string; description: string | null; baseSessions: number; durationMinutes: number | null; priceCents: number; active: boolean; sessionSchema: Record<string, unknown> };
type Anamnesis = { id: string; title: string; versions: { id: string; version: number; schema: Record<string, unknown> }[] };
type PatientHistory = { patient: Patient; events: { type: string; at: string; title: string; details?: any }[]; pending: { type: string; at: string; title: string }[] };
type Pack = { id: string; name: string; priceCents: number; promotionalPriceCents: number | null; items: { procedureId: string; sessionsOverride: number | null }[] };
type Plan = { id: string; patientId: string; offerName: string; priceCents: number; items: { id: string; procedureName: string; sessionsTotal: number }[]; payments: { amountCents: number }[] };
type Appointment = { id: string; patientId: string; startsAt: string; endsAt: string; status: string; items: { planItemId: string }[] };
type ApiResult<T> = { data?: T; error?: string };
const currency = (cents: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100);
const emptySchema = { type: 'object', properties: {} } as Record<string, unknown>;

function useApi<T>(path: string) {
  const [result, setResult] = useState<ApiResult<T>>({}); const [reload, setReload] = useState(0);
  useEffect(() => { let active = true; fetch(path).then(async (res) => { if (!res.ok) throw new Error('Não foi possível carregar os dados.'); return res.json() as Promise<T>; }).then((data) => active && setResult({ data })).catch((error: Error) => active && setResult({ error: error.message })); return () => { active = false; }; }, [path, reload]);
  return { ...result, refresh: () => setReload((value) => value + 1) };
}

function App() {
  const patientsApi = useApi<Patient[]>('/api/patients'); const proceduresApi = useApi<Procedure[]>('/api/procedures');
  const anamnesesApi = useApi<Anamnesis[]>('/api/anamneses'); const contractsApi = useApi<any[]>('/api/contracts');
  const packagesApi = useApi<Pack[]>('/api/packages'); const plansApi = useApi<Plan[]>('/api/plans');
  const appointmentsApi = useApi<Appointment[]>('/api/appointments'); const sessionsApi = useApi<any[]>('/api/sessions');
  const patients = patientsApi.data ?? [], procedures = proceduresApi.data ?? [], plans = plansApi.data ?? [];
  const [query, setQuery] = useState(''), [activeView, setActiveView] = useState('Visão geral');
  const [showPatientForm, setShowPatientForm] = useState(false), [showProcedureForm, setShowProcedureForm] = useState(false);
  const [showAnamnesisForm, setShowAnamnesisForm] = useState(false), [showContractForm, setShowContractForm] = useState(false), [showPackForm, setShowPackForm] = useState(false);
  const [notice, setNotice] = useState(''), [selectedPatient, setSelectedPatient] = useState<string | null>(null);
  const [sessionSchema, setSessionSchema] = useState<Record<string, unknown>>(emptySchema), [patientHistory, setPatientHistory] = useState<PatientHistory | null>(null);
  const [calendarSelection, setCalendarSelection] = useState<{ start: string; end: string } | null>(null), [patientFormToken, setPatientFormToken] = useState<string | null>(null), [publicFormToken, setPublicFormToken] = useState<string | null>(null);
  const [publicForm, setPublicForm] = useState<{ token: string; schema: any; draft: any; title: string } | null>(null);
  const [selectedAnamnesis, setSelectedAnamnesis] = useState<Anamnesis | null>(null);
  const [paymentPlan, setPaymentPlan] = useState<Plan | null>(null), [sessionPlanItem, setSessionPlanItem] = useState<any>(null);
  const filteredPatients = useMemo(() => patients.filter((patient) => patient.fullName.toLowerCase().includes(query.toLowerCase()) || patient.phone?.includes(query)), [patients, query]);
  const navigation = [{ label: 'Visão geral', icon: LayoutDashboard }, { label: 'Pacientes', icon: UsersRound }, { label: 'Agenda', icon: CalendarDays }, { label: 'Procedimentos', icon: Sparkles }, { label: 'Anamneses', icon: ClipboardList }, { label: 'Contratos', icon: FileText }, { label: 'Financeiro', icon: WalletCards }];
  const refreshAll = () => { patientsApi.refresh(); proceduresApi.refresh(); anamnesesApi.refresh(); contractsApi.refresh(); packagesApi.refresh(); plansApi.refresh(); appointmentsApi.refresh(); sessionsApi.refresh(); };
  async function apiPost(url: string, body: unknown) { const res = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.error ?? 'Não foi possível concluir.'); return data; }
  async function createPatient(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiPost('/api/patients', { fullName: form.get('fullName'), phone: form.get('phone'), email: form.get('email') }); setShowPatientForm(false); setNotice('Paciente cadastrado.'); patientsApi.refresh(); } catch (error) { setNotice((error as Error).message); } }
  async function createProcedure(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiPost('/api/procedures', { name: form.get('name'), description: form.get('description'), baseSessions: Number(form.get('baseSessions')), durationMinutes: Number(form.get('durationMinutes')) || null, priceCents: Math.round(Number(form.get('price')) * 100), sessionSchema }); setShowProcedureForm(false); setNotice('Procedimento cadastrado.'); proceduresApi.refresh(); } catch (error) { setNotice((error as Error).message); } }
  async function createAnamnesis(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiPost('/api/anamneses', { title: form.get('title'), schema: sessionSchema }); setShowAnamnesisForm(false); setSessionSchema(emptySchema); anamnesesApi.refresh(); setNotice('Anamnese criada.'); } catch (error) { setNotice((error as Error).message); } }
  async function createContract(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiPost('/api/contracts', { title: form.get('title'), kind: form.get('kind'), content: form.get('content') }); setShowContractForm(false); contractsApi.refresh(); setNotice('Contrato criado.'); } catch (error) { setNotice((error as Error).message); } }
  async function createPackage(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const procedureId = String(form.get('procedureId')); try { await apiPost('/api/packages', { name: form.get('name'), priceCents: Math.round(Number(form.get('price')) * 100), promotionalPriceCents: form.get('promo') ? Math.round(Number(form.get('promo')) * 100) : null, validUntil: form.get('validUntil') || null, items: [{ procedureId, sessionsOverride: Number(form.get('sessionsOverride')) || null }] }); setShowPackForm(false); packagesApi.refresh(); setNotice('Pacote cadastrado.'); } catch (error) { setNotice((error as Error).message); } }
  async function openPatient(patient: Patient) { setSelectedPatient(patient.id); try { const res = await fetch(`/api/patients/${patient.id}/history`); setPatientHistory(await res.json()); } catch { setPatientHistory(null); } }
  async function requestAnamnesis(patientId: string, anamnesisId: string) { try { const applied = await apiPost('/api/patient-anamneses', { patientId, anamnesisId }); const request = await apiPost('/api/anamnesis-requests', { patientAnamnesisId: applied.id }); setPatientFormToken(`${location.origin}${request.url}`); setNotice('Link criado — copie e envie ao paciente.'); } catch (error) { setNotice((error as Error).message); } }
  async function submitPlan(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiPost('/api/plans', { patientId: form.get('patientId'), offerType: form.get('offerType'), offerId: form.get('offerId'), priceCents: Math.round(Number(form.get('price')) * 100) }); setNotice('Contratação registrada.'); refreshAll(); } catch (error) { setNotice((error as Error).message); } }
  async function saveAppointment(selection: DateSelectArg, event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiPost('/api/appointments', { patientId: form.get('patientId'), planItemIds: [form.get('planItemId')], startsAt: selection.start.toISOString(), endsAt: selection.end.toISOString(), status: 'planned' }); setCalendarSelection(null); appointmentsApi.refresh(); setNotice('Agendamento criado.'); } catch (error) { setNotice((error as Error).message); } }
  async function addPayment(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (!paymentPlan) return; try { await apiPost('/api/payments', { planId: paymentPlan.id, amountCents: Math.round(Number(form.get('amount')) * 100), method: form.get('method'), installments: Number(form.get('installments')) || 1 }); setPaymentPlan(null); plansApi.refresh(); setNotice('Pagamento registrado.'); } catch (error) { setNotice((error as Error).message); } }
  async function saveSession(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (!sessionPlanItem) return; const data: Record<string, unknown> = {}; for (const [key, value] of form.entries()) if (key.startsWith('field:')) data[key.slice(6)] = value; try { await apiPost('/api/sessions', { planItemId: sessionPlanItem.id, appointmentId: form.get('appointmentId') || null, data, notes: form.get('notes') }); setSessionPlanItem(null); refreshAll(); setNotice('Sessão registrada como realizada.'); } catch (error) { setNotice((error as Error).message); } }
  async function loadPublicForm(token: string) { const res = await fetch(`/public/anamnesis/${token}`); if (!res.ok) { setNotice('Link inválido, expirado ou já enviado.'); return; } const data = await res.json(); setPublicForm({ token, ...data }); }

  const currentPatientPlans = plans.filter((plan) => plan.patientId === selectedPatient);
  const calendarEvents = (appointmentsApi.data ?? []).map((a) => ({ id: a.id, title: `${patients.find((p) => p.id === a.patientId)?.fullName ?? 'Paciente'} · ${a.status}`, start: a.startsAt, end: a.endsAt, extendedProps: { appointment: a } }));
  const viewTitle: Record<string, string> = { 'Visão geral': 'Sua clínica, em um só lugar.', Pacientes: 'Pacientes', Agenda: 'Agenda semanal', Procedimentos: 'Procedimentos e pacotes', Anamneses: 'Formulários de anamnese', Contratos: 'Contratos da clínica', Financeiro: 'Contratações e pagamentos' };
  const visiblePlans = plans;
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#inicio"><span className="brand-mark"><Activity size={19} /></span><span>clínicare<span className="brand-dot">.</span></span></a><div className="clinic-switch"><span className="clinic-avatar">V</span><span className="clinic-label"><strong>Clínica Vitta</strong><small>Estética & bem-estar</small></span><ChevronDown size={15} /></div><div className="nav-caption">MENU PRINCIPAL</div><nav aria-label="Menu principal">{navigation.map(({ label, icon: Icon }) => <button key={label} className={`nav-link ${activeView === label ? 'active' : ''}`} onClick={() => setActiveView(label)}><Icon size={18} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-link"><Settings2 size={18} /><span>Configurações</span></button><div className="help-card"><span className="help-icon"><CircleHelp size={17} /></span><div><strong>Ambiente de teste</strong><small>Use apenas dados fictícios</small></div></div><div className="profile-row"><div className="profile-avatar">AD</div><div className="profile-copy"><strong>Administradora</strong><small>Clínica Vitta</small></div></div></div></aside>
    <main className="main-area"><header className="topbar"><div className="breadcrumb">Clínica Vitta <ChevronRight size={14} /> <strong>{activeView}</strong></div><div className="topbar-right"><span className="prototype-tag">PROTÓTIPO · DADOS FICTÍCIOS</span><span className="date-chip"><CalendarDays size={15} /> {new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full' }).format(new Date())}</span></div></header>
      <div className="content-wrap">{notice && <div className="notice" role="status">{notice}{patientFormToken && <button onClick={() => navigator.clipboard.writeText(patientFormToken)}>Copiar link</button>}<button onClick={() => { setNotice(''); setPatientFormToken(null); }}>×</button></div>}
      {publicForm ? <section className="public-form-card"><button className="text-button" onClick={() => setPublicForm(null)}>← Voltar</button><div className="section-kicker">FORMULÁRIO DA CLÍNICA</div><h1>{publicForm.title}</h1><p>Preencha com atenção. Ao enviar, suas respostas ficam registradas.</p><SchemaForm schema={publicForm.schema} value={publicForm.draft} onChange={(draft) => setPublicForm({ ...publicForm, draft })} /><div className="modal-actions"><button className="secondary-button" onClick={async () => { await fetch(`/public/anamnesis/${publicForm.token}/draft`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ draft: publicForm.draft }) }); setNotice('Rascunho salvo.'); }}>Salvar rascunho</button><button className="primary-button" onClick={async () => { const res = await fetch(`/public/anamnesis/${publicForm.token}/submit`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ answers: publicForm.draft }) }); if (res.ok) { setPublicForm(null); setNotice('Anamnese enviada. Obrigado!'); } else setNotice('Não foi possível enviar.'); }}>Enviar anamnese</button></div></section> : <>
      <section className="welcome-row"><div><div className="eyebrow"><span className="eyebrow-line" /> AMBIENTE DE DEMONSTRAÇÃO</div><h1>{viewTitle[activeView] ?? activeView}</h1><p className="welcome-subtitle">Gestão de pacientes, procedimentos e cuidados.</p></div><button className="primary-button" onClick={() => setShowPatientForm(true)}><Plus size={17} /> Novo paciente</button></section>
      {activeView === 'Visão geral' && <><section className="stats-grid"><article className="stat-card"><div className="stat-heading">Pacientes cadastrados <span className="stat-icon violet"><UsersRound size={17} /></span></div><div className="stat-value">{patients.length}<span className="stat-suffix"> no total</span></div><div className="stat-foot">Base da clínica</div></article><article className="stat-card"><div className="stat-heading">Procedimentos ativos <span className="stat-icon peach"><Sparkles size={17} /></span></div><div className="stat-value">{procedures.length}<span className="stat-suffix"> cadastrados</span></div><div className="stat-foot">Catálogo da clínica</div></article><article className="stat-card"><div className="stat-heading">Agendamentos <span className="stat-icon blue"><CalendarDays size={17} /></span></div><div className="stat-value">{(appointmentsApi.data ?? []).length}<span className="stat-suffix"> marcados</span></div><div className="stat-foot">Calendário semanal</div></article><article className="stat-card"><div className="stat-heading">Planos ativos <span className="stat-icon mint"><Activity size={17} /></span></div><div className="stat-value">{plans.length}<span className="stat-suffix"> contratados</span></div><div className="stat-foot">Acompanhamento</div></article></section><section className="data-grid"><article className="panel"><div className="panel-header"><div><div className="section-kicker">RELACIONAMENTO</div><h2>Pacientes recentes</h2></div></div><label className="search-box"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar paciente por nome ou telefone" /></label>{filteredPatients.slice(0, 5).map((p) => <button className="patient-row" key={p.id} onClick={() => openPatient(p)}><span className="patient-initials">{p.fullName.slice(0, 2).toUpperCase()}</span><span className="patient-info"><strong>{p.fullName}</strong><small>{p.phone || p.email || 'Sem contato'}</small></span><ChevronRight size={16} /></button>)}</article><article className="panel"><div className="panel-header"><div><div className="section-kicker">EXECUÇÃO</div><h2>Próximas sessões</h2></div><button className="text-button" onClick={() => setActiveView('Agenda')}>Abrir agenda</button></div>{(appointmentsApi.data ?? []).slice(0, 4).map((a) => <div className="procedure-row" key={a.id}><CalendarDays size={18} /><span className="procedure-info"><strong>{patients.find((p) => p.id === a.patientId)?.fullName ?? 'Paciente'}</strong><small>{new Date(a.startsAt).toLocaleString('pt-BR')}</small></span></div>)}</article></section></>}
      {activeView === 'Pacientes' && <section className="panel"><div className="panel-header"><h2>Pacientes</h2><button className="primary-button" onClick={() => setShowPatientForm(true)}>＋ Novo paciente</button></div><label className="search-box"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nome ou telefone" /></label>{filteredPatients.map((p) => <button className="patient-row" key={p.id} onClick={() => openPatient(p)}><span className="patient-initials">{p.fullName.slice(0, 2).toUpperCase()}</span><span className="patient-info"><strong>{p.fullName}</strong><small>{p.phone || p.email || 'Sem contato'}</small></span><ChevronRight size={16} /></button>)}</section>}
      {activeView === 'Procedimentos' && <><section className="panel"><div className="panel-header"><h2>Catálogo de procedimentos</h2><button className="primary-button" onClick={() => setShowProcedureForm(true)}>＋ Novo procedimento</button></div>{procedures.map((p) => <div className="procedure-row" key={p.id}><Sparkles size={18} /><span className="procedure-info"><strong>{p.name}</strong><small>{p.baseSessions} sessões base · {p.durationMinutes ?? 'Duração flexível'} min</small></span><strong>{currency(p.priceCents)}</strong></div>)}</section><section className="panel"><div className="panel-header"><h2>Pacotes</h2><button className="secondary-button" onClick={() => setShowPackForm(true)}>＋ Novo pacote</button></div>{(packagesApi.data ?? []).map((pack) => <div className="procedure-row" key={pack.id}><Sparkles size={18} /><span className="procedure-info"><strong>{pack.name}</strong><small>{pack.items.length} procedimentos</small></span><strong>{currency(pack.promotionalPriceCents ?? pack.priceCents)}</strong></div>)}</section></>}
      {activeView === 'Anamneses' && <section className="panel"><div className="panel-header"><h2>Formulários de anamnese</h2><button className="primary-button" onClick={() => { setSessionSchema(emptySchema); setShowAnamnesisForm(true); }}>＋ Nova anamnese</button></div>{(anamnesesApi.data ?? []).map((a) => <div className="procedure-row" key={a.id}><ClipboardList size={18} /><span className="procedure-info"><strong>{a.title}</strong><small>{a.versions.length} versões · atual v{a.versions[0]?.version}</small></span><div className="row-actions">{a.versions.slice(0, 3).map((v) => <button className="text-button" key={v.id} onClick={async () => { try { await apiPost(`/api/anamneses/${a.id}/versions`, { restoreVersion: v.version }); anamnesesApi.refresh(); setNotice(`Versão ${v.version} restaurada como nova versão.`); } catch (error) { setNotice((error as Error).message); } }}>Restaurar v{v.version}</button>)}</div></div>)}</section>}
      {activeView === 'Contratos' && <section className="panel"><div className="panel-header"><h2>Contratos e documentos modelo</h2><button className="primary-button" onClick={() => setShowContractForm(true)}>＋ Novo contrato</button></div>{(contractsApi.data ?? []).map((c) => <div className="procedure-row" key={c.id}><FileText size={18} /><span className="procedure-info"><strong>{c.title}</strong><small>{c.kind} · {c.versions?.length} versões</small></span><button className="text-button" onClick={async () => { const latest = c.versions?.[0]; if (latest) { const res = await fetch(`/api/contracts/${c.id}/versions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ restoreVersion: latest.version }) }); if (res.ok) contractsApi.refresh(); } }}>Criar nova versão</button></div>)}<p className="section-note">Assinatura digital não faz parte desta versão do protótipo.</p></section>}
      {activeView === 'Financeiro' && <section className="panel"><div className="panel-header"><h2>Contratações</h2><button className="primary-button" onClick={() => setShowPatientForm(true)}>＋ Cadastrar paciente</button></div>{visiblePlans.map((plan) => <div className="procedure-row" key={plan.id}><WalletCards size={18} /><span className="procedure-info"><strong>{plan.offerName}</strong><small>{patients.find((p) => p.id === plan.patientId)?.fullName} · recebido {currency(plan.payments.reduce((s, p) => s + p.amountCents, 0))} de {currency(plan.priceCents)}</small></span><button className="text-button" onClick={() => setPaymentPlan(plan)}>Registrar pagamento</button></div>)}{patients.length > 0 && <form className="inline-create" onSubmit={submitPlan}><h3>Registrar nova contratação</h3><select name="patientId" required>{patients.map((p) => <option key={p.id} value={p.id}>{p.fullName}</option>)}</select><select name="offerType"><option value="procedure">Procedimento</option><option value="package">Pacote</option></select><select name="offerId" required><optgroup label="Procedimentos">{procedures.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</optgroup><optgroup label="Pacotes">{(packagesApi.data ?? []).map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</optgroup></select><input name="price" type="number" min="0" step="0.01" placeholder="Preço contratado R$" required /><button className="primary-button">Registrar contratação</button></form>}</section>}
      {activeView === 'Agenda' && <section className="panel"><div className="panel-header"><div><div className="section-kicker">AGENDA DO PROFISSIONAL</div><h2>Semana de atendimentos</h2></div></div><CalendarView events={calendarEvents as any} onSelect={(selection: DateSelectArg) => setCalendarSelection({ start: selection.startStr, end: selection.endStr })} onOpen={(event: EventClickArg) => setNotice(`Agendamento: ${event.event.title}`)} /></section>}
      {selectedPatient && patientHistory && <div className="modal-backdrop" onClick={(e) => e.target === e.currentTarget && setSelectedPatient(null)}><section className="modal patient-detail"><button className="text-button" onClick={() => setSelectedPatient(null)}>← Voltar</button><h2>{patientHistory.patient.fullName}</h2><p>{patientHistory.patient.phone} · {patientHistory.patient.email}</p><div className="row-actions"><button className="secondary-button" onClick={() => anamnesesApi.data?.[0] && requestAnamnesis(selectedPatient, anamnesesApi.data[0].id)}>Solicitar anamnese</button><button className="secondary-button" onClick={() => { const plan = plans.find((p) => p.patientId === selectedPatient); const item = plan?.items[0]; if (item) setSessionPlanItem(item); else setNotice('Contrate um procedimento antes de registrar sessão.'); }}>Registrar sessão</button></div><h3>Pendências</h3>{patientHistory.pending.map((e, i) => <div className="procedure-row" key={i}>{e.title}</div>)}<h3>Histórico</h3>{patientHistory.events.map((e, i) => <div className="history-event" key={i}><time>{new Date(e.at).toLocaleString('pt-BR')}</time><strong>{e.title}</strong><small>{e.type}</small></div>)}{plans.filter((p) => p.patientId === selectedPatient).map((plan) => <div key={plan.id} className="plan-card"><strong>{plan.offerName} · {currency(plan.priceCents)}</strong>{plan.items.map((item) => <div className="procedure-row" key={item.id}>{item.procedureName} — {item.sessionsTotal} sessões</div>)}<button className="secondary-button" onClick={() => { const a = anamnesesApi.data?.[0]; if (a) requestAnamnesis(selectedPatient, a.id); }}>Solicitar anamnese</button></div>)}</section></div>}
      </>}
      <footer className="page-footer"><span>Clínicare <span className="brand-dot">.</span> Gestão feita com cuidado.</span><span>Protótipo · Dados fictícios</span></footer></div></main>
    {showPatientForm && <div className="modal-backdrop" onClick={(e) => e.target === e.currentTarget && setShowPatientForm(false)}><form className="modal" onSubmit={createPatient}><div className="modal-kicker">NOVO CADASTRO</div><h2>Cadastrar paciente</h2><label>Nome completo<input name="fullName" required autoFocus /></label><label>Telefone<input name="phone" /></label><label>E-mail<input name="email" type="email" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowPatientForm(false)}>Cancelar</button><button className="primary-button">Salvar paciente</button></div></form></div>}
    {showProcedureForm && <div className="modal-backdrop" onClick={(e) => e.target === e.currentTarget && setShowProcedureForm(false)}><form className="modal wide-modal" onSubmit={createProcedure}><div className="modal-kicker">CATÁLOGO DA CLÍNICA</div><h2>Novo procedimento</h2><label>Nome<input name="name" required autoFocus /></label><label>Descrição<input name="description" /></label><div className="form-columns"><label>Sessões base<input name="baseSessions" type="number" min="1" defaultValue="1" required /></label><label>Duração (minutos)<input name="durationMinutes" type="number" min="0" placeholder="Opcional" /></label><label>Preço padrão R$<input name="price" type="number" min="0" step="0.01" defaultValue="0" required /></label></div><SchemaEditor value={sessionSchema as any} onChange={setSessionSchema} /><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowProcedureForm(false)}>Cancelar</button><button className="primary-button">Salvar procedimento</button></div></form></div>}
    {showAnamnesisForm && <div className="modal-backdrop"><form className="modal wide-modal" onSubmit={createAnamnesis}><div className="modal-kicker">JSON SCHEMA FORM</div><h2>Nova anamnese</h2><label>Nome do formulário<input name="title" required autoFocus /></label><SchemaEditor value={sessionSchema as any} onChange={setSessionSchema} /><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowAnamnesisForm(false)}>Cancelar</button><button className="primary-button">Salvar anamnese</button></div></form></div>}
    {showContractForm && <div className="modal-backdrop"><form className="modal" onSubmit={createContract}><h2>Novo contrato</h2><label>Nome do documento<input name="title" required /></label><label>Aplicação<select name="kind"><option value="standard">Padrão de serviço</option><option value="procedure">Específico de procedimento</option><option value="package">Específico de pacote</option></select></label><label>Conteúdo do documento<textarea name="content" rows={8} placeholder="Escreva o conteúdo do modelo. Importação DOCX fica disponível ao configurar R2." /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowContractForm(false)}>Cancelar</button><button className="primary-button">Salvar versão 1</button></div></form></div>}
    {showPackForm && <div className="modal-backdrop"><form className="modal" onSubmit={createPackage}><h2>Novo pacote</h2><label>Nome<input name="name" required /></label><label>Procedimento<select name="procedureId" required>{procedures.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Sessões (opcional; substitui padrão)<input name="sessionsOverride" type="number" min="1" /></label><label>Preço padrão R$<input name="price" type="number" min="0" step="0.01" required /></label><label>Preço promocional R$<input name="promo" type="number" min="0" step="0.01" /></label><label>Válido até<input name="validUntil" type="date" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowPackForm(false)}>Cancelar</button><button className="primary-button">Salvar pacote</button></div></form></div>}
    {calendarSelection && <div className="modal-backdrop"><form className="modal" onSubmit={(event) => saveAppointment({ start: new Date(calendarSelection.start), end: new Date(calendarSelection.end), startStr: calendarSelection.start, endStr: calendarSelection.end } as DateSelectArg, event)}><h2>Novo agendamento</h2><label>Paciente<select name="patientId" required>{patients.map((p) => <option key={p.id} value={p.id}>{p.fullName}</option>)}</select></label><label>Procedimento contratado<select name="planItemId" required>{plans.flatMap((p) => p.items.map((i) => <option key={i.id} value={i.id}>{patients.find((x) => x.id === p.patientId)?.fullName} · {i.procedureName}</option>))}</select></label><p>{new Date(calendarSelection.start).toLocaleString('pt-BR')} – {new Date(calendarSelection.end).toLocaleTimeString('pt-BR')}</p><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setCalendarSelection(null)}>Cancelar</button><button className="primary-button">Agendar</button></div></form></div>}
    {paymentPlan && <div className="modal-backdrop"><form className="modal" onSubmit={addPayment}><h2>Registrar pagamento</h2><p>{paymentPlan.offerName} · total {currency(paymentPlan.priceCents)}</p><label>Valor recebido R$<input name="amount" type="number" step="0.01" min="0.01" required /></label><label>Forma de pagamento<select name="method"><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="credit_card">Cartão de crédito</option></select></label><label>Parcelas<input name="installments" type="number" min="1" defaultValue="1" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setPaymentPlan(null)}>Cancelar</button><button className="primary-button">Registrar</button></div></form></div>}
    {sessionPlanItem && <div className="modal-backdrop"><form className="modal" onSubmit={saveSession}><h2>Registrar sessão realizada</h2><p>{sessionPlanItem.procedureName}</p>{Object.entries((sessionPlanItem.sessionSchema?.properties ?? {}) as Record<string, any>).map(([key, schema]) => <label key={key}>{schema.title ?? key}<input name={`field:${key}`} type={schema.type === 'number' ? 'number' : 'text'} required={sessionPlanItem.sessionSchema.required?.includes(key)} /></label>)}<label>Observações<textarea name="notes" rows={3} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setSessionPlanItem(null)}>Cancelar</button><button className="primary-button">Salvar sessão</button></div></form></div>}
    {selectedAnamnesis && <div className="modal-backdrop"><form className="modal" onSubmit={async (e) => { e.preventDefault(); const form = new FormData(e.currentTarget); const response = await fetch(`/public/anamnesis/${publicFormToken}/submit`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ answers: Object.fromEntries(form) }) }); if (response.ok) { setSelectedAnamnesis(null); setPublicFormToken(null); setNotice('Anamnese recebida.'); } }}><h2>{selectedAnamnesis.title}</h2><SchemaForm schema={selectedAnamnesis.versions[0].schema as any} onChange={() => {}} /><button className="primary-button">Enviar</button></form></div>}
    </div>;
}
export default App;
