/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppAnamnesesRouteImport } from './routes/_app/anamneses'
import { Route as AppContratosRouteImport } from './routes/_app/contratos'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppPacientesRouteImport } from './routes/_app/pacientes'
import { Route as AppProcedimentosRouteImport } from './routes/_app/procedimentos'
import { Route as FormularioTokenRouteImport } from './routes/formulario.$token'
import { Route as AppPacientesPatientIdRouteImport } from './routes/_app/pacientes.$patientId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAnamnesesRoute = AppAnamnesesRouteImport.update({
  id: '/anamneses',
  path: '/anamneses',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppProcedimentosRoute = AppProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => AppRoute,
} as any)
const FormularioTokenRoute = FormularioTokenRouteImport.update({
  id: '/formulario/$token',
  path: '/formulario/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPacientesPatientIdRoute = AppPacientesPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => AppPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agenda': typeof AppAgendaRoute
  '/anamneses': typeof AppAnamnesesRoute
  '/contratos': typeof AppContratosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/procedimentos': typeof AppProcedimentosRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/pacientes/$patientId': typeof AppPacientesPatientIdRoute
}
export interface FileRoutesByTo {
  '/agenda': typeof AppAgendaRoute
  '/anamneses': typeof AppAnamnesesRoute
  '/contratos': typeof AppContratosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/procedimentos': typeof AppProcedimentosRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/': typeof AppIndexRoute
  '/pacientes/$patientId': typeof AppPacientesPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/anamneses': typeof AppAnamnesesRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/pacientes': typeof AppPacientesRouteWithChildren
  '/_app/procedimentos': typeof AppProcedimentosRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pacientes/$patientId': typeof AppPacientesPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/anamneses'
    | '/contratos'
    | '/financeiro'
    | '/pacientes'
    | '/procedimentos'
    | '/formulario/$token'
    | '/pacientes/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agenda'
    | '/anamneses'
    | '/contratos'
    | '/financeiro'
    | '/pacientes'
    | '/procedimentos'
    | '/formulario/$token'
    | '/'
    | '/pacientes/$patientId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agenda'
    | '/_app/anamneses'
    | '/_app/contratos'
    | '/_app/financeiro'
    | '/_app/pacientes'
    | '/_app/procedimentos'
    | '/formulario/$token'
    | '/_app/'
    | '/_app/pacientes/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  FormularioTokenRoute: typeof FormularioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anamneses': {
      id: '/_app/anamneses'
      path: '/anamneses'
      fullPath: '/anamneses'
      preLoaderRoute: typeof AppAnamnesesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procedimentos': {
      id: '/_app/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof AppProcedimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/formulario/$token': {
      id: '/formulario/$token'
      path: '/formulario/$token'
      fullPath: '/formulario/$token'
      preLoaderRoute: typeof FormularioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pacientes/$patientId': {
      id: '/_app/pacientes/$patientId'
      path: '/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof AppPacientesPatientIdRouteImport
      parentRoute: typeof AppPacientesRoute
    }
  }
}

interface AppPacientesRouteChildren {
  AppPacientesPatientIdRoute: typeof AppPacientesPatientIdRoute
}

const AppPacientesRouteChildren: AppPacientesRouteChildren = {
  AppPacientesPatientIdRoute: AppPacientesPatientIdRoute,
}

const AppPacientesRouteWithChildren = AppPacientesRoute._addFileChildren(
  AppPacientesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAnamnesesRoute: typeof AppAnamnesesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppPacientesRoute: typeof AppPacientesRouteWithChildren
  AppProcedimentosRoute: typeof AppProcedimentosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAnamnesesRoute: AppAnamnesesRoute,
  AppContratosRoute: AppContratosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppPacientesRoute: AppPacientesRouteWithChildren,
  AppProcedimentosRoute: AppProcedimentosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  FormularioTokenRoute: FormularioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
