/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppDocumentosRouteImport } from './routes/_app/documentos'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AssinaturaTokenRouteImport } from './routes/assinatura.$token'
import { Route as FormularioTokenRouteImport } from './routes/formulario.$token'
import { Route as AppContratosIndexRouteImport } from './routes/_app/contratos/index'
import { Route as AppContratosContractIdRouteImport } from './routes/_app/contratos/$contractId'
import { Route as AppContratosNovoRouteImport } from './routes/_app/contratos/novo'
import { Route as AppEventosIndexRouteImport } from './routes/_app/eventos/index'
import { Route as AppFormulariosAnamneseIndexRouteImport } from './routes/_app/formularios-anamnese/index'
import { Route as AppFormulariosAnamneseAnamnesisIdRouteImport } from './routes/_app/formularios-anamnese/$anamnesisId'
import { Route as AppFormulariosAnamneseNovaRouteImport } from './routes/_app/formularios-anamnese/nova'
import { Route as AppPacientesIndexRouteImport } from './routes/_app/pacientes/index'
import { Route as AppPacientesNovoRouteImport } from './routes/_app/pacientes/novo'
import { Route as AppPlanosIndexRouteImport } from './routes/_app/planos/index'
import { Route as AppPlanosNovoRouteImport } from './routes/_app/planos/novo'
import { Route as AppProcedimentosIndexRouteImport } from './routes/_app/procedimentos/index'
import { Route as AppProcedimentosProcedureIdRouteImport } from './routes/_app/procedimentos/$procedureId'
import { Route as AppProcedimentosNovoRouteImport } from './routes/_app/procedimentos/novo'
import { Route as AppPacientesPatientIdIndexRouteImport } from './routes/_app/pacientes/$patientId/index'
import { Route as AppPacientesPatientIdRelacionamentoRouteImport } from './routes/_app/pacientes/$patientId/relacionamento'
import { Route as AppProcedimentosCombosComboIdRouteImport } from './routes/_app/procedimentos/combos/$comboId'
import { Route as AppProcedimentosCombosNovoRouteImport } from './routes/_app/procedimentos/combos/novo'
import { Route as AppPacientesPatientIdAnamnesesFormIdRouteImport } from './routes/_app/pacientes/$patientId/anamneses.$formId'
import { Route as AppPacientesPatientIdAtendimentosAttendanceIdRouteImport } from './routes/_app/pacientes/$patientId/atendimentos.$attendanceId'
import { Route as AppPacientesPatientIdAvulsoProcedureIdRouteImport } from './routes/_app/pacientes/$patientId/avulso.$procedureId'
import { Route as AppPacientesPatientIdNovoAtendimentoItemIdRouteImport } from './routes/_app/pacientes/$patientId/novo-atendimento.$itemId'
import { Route as AppPacientesPatientIdAnamnesesFormIdRespostasRouteImport } from './routes/_app/pacientes/$patientId/anamneses.$formId.respostas'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AssinaturaTokenRoute = AssinaturaTokenRouteImport.update({
  id: '/assinatura/$token',
  path: '/assinatura/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioTokenRoute = FormularioTokenRouteImport.update({
  id: '/formulario/$token',
  path: '/formulario/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContratosIndexRoute = AppContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosContractIdRoute = AppContratosContractIdRouteImport.update({
  id: '/contratos/$contractId',
  path: '/contratos/$contractId',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosNovoRoute = AppContratosNovoRouteImport.update({
  id: '/contratos/novo',
  path: '/contratos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosIndexRoute = AppEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormulariosAnamneseIndexRoute =
  AppFormulariosAnamneseIndexRouteImport.update({
    id: '/formularios-anamnese/',
    path: '/formularios-anamnese/',
    getParentRoute: () => AppRoute,
  } as any)
const AppFormulariosAnamneseAnamnesisIdRoute =
  AppFormulariosAnamneseAnamnesisIdRouteImport.update({
    id: '/formularios-anamnese/$anamnesisId',
    path: '/formularios-anamnese/$anamnesisId',
    getParentRoute: () => AppRoute,
  } as any)
const AppFormulariosAnamneseNovaRoute =
  AppFormulariosAnamneseNovaRouteImport.update({
    id: '/formularios-anamnese/nova',
    path: '/formularios-anamnese/nova',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesNovoRoute = AppPacientesNovoRouteImport.update({
  id: '/pacientes/novo',
  path: '/pacientes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosIndexRoute = AppPlanosIndexRouteImport.update({
  id: '/planos/',
  path: '/planos/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosNovoRoute = AppPlanosNovoRouteImport.update({
  id: '/planos/novo',
  path: '/planos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppProcedimentosIndexRoute = AppProcedimentosIndexRouteImport.update({
  id: '/procedimentos/',
  path: '/procedimentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcedimentosProcedureIdRoute =
  AppProcedimentosProcedureIdRouteImport.update({
    id: '/procedimentos/$procedureId',
    path: '/procedimentos/$procedureId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProcedimentosNovoRoute = AppProcedimentosNovoRouteImport.update({
  id: '/procedimentos/novo',
  path: '/procedimentos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesPatientIdIndexRoute =
  AppPacientesPatientIdIndexRouteImport.update({
    id: '/pacientes/$patientId/',
    path: '/pacientes/$patientId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacientesPatientIdRelacionamentoRoute =
  AppPacientesPatientIdRelacionamentoRouteImport.update({
    id: '/pacientes/$patientId/relacionamento',
    path: '/pacientes/$patientId/relacionamento',
    getParentRoute: () => AppRoute,
  } as any)
const AppProcedimentosCombosComboIdRoute =
  AppProcedimentosCombosComboIdRouteImport.update({
    id: '/procedimentos/combos/$comboId',
    path: '/procedimentos/combos/$comboId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProcedimentosCombosNovoRoute =
  AppProcedimentosCombosNovoRouteImport.update({
    id: '/procedimentos/combos/novo',
    path: '/procedimentos/combos/novo',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacientesPatientIdAnamnesesFormIdRoute =
  AppPacientesPatientIdAnamnesesFormIdRouteImport.update({
    id: '/pacientes/$patientId/anamneses/$formId',
    path: '/pacientes/$patientId/anamneses/$formId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacientesPatientIdAtendimentosAttendanceIdRoute =
  AppPacientesPatientIdAtendimentosAttendanceIdRouteImport.update({
    id: '/pacientes/$patientId/atendimentos/$attendanceId',
    path: '/pacientes/$patientId/atendimentos/$attendanceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacientesPatientIdAvulsoProcedureIdRoute =
  AppPacientesPatientIdAvulsoProcedureIdRouteImport.update({
    id: '/pacientes/$patientId/avulso/$procedureId',
    path: '/pacientes/$patientId/avulso/$procedureId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacientesPatientIdNovoAtendimentoItemIdRoute =
  AppPacientesPatientIdNovoAtendimentoItemIdRouteImport.update({
    id: '/pacientes/$patientId/novo-atendimento/$itemId',
    path: '/pacientes/$patientId/novo-atendimento/$itemId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacientesPatientIdAnamnesesFormIdRespostasRoute =
  AppPacientesPatientIdAnamnesesFormIdRespostasRouteImport.update({
    id: '/respostas',
    path: '/respostas',
    getParentRoute: () => AppPacientesPatientIdAnamnesesFormIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/documentos': typeof AppDocumentosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/assinatura/$token': typeof AssinaturaTokenRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/contratos/$contractId': typeof AppContratosContractIdRoute
  '/contratos/novo': typeof AppContratosNovoRoute
  '/formularios-anamnese/$anamnesisId': typeof AppFormulariosAnamneseAnamnesisIdRoute
  '/formularios-anamnese/nova': typeof AppFormulariosAnamneseNovaRoute
  '/pacientes/novo': typeof AppPacientesNovoRoute
  '/planos/novo': typeof AppPlanosNovoRoute
  '/procedimentos/$procedureId': typeof AppProcedimentosProcedureIdRoute
  '/procedimentos/novo': typeof AppProcedimentosNovoRoute
  '/contratos/': typeof AppContratosIndexRoute
  '/eventos/': typeof AppEventosIndexRoute
  '/formularios-anamnese/': typeof AppFormulariosAnamneseIndexRoute
  '/pacientes/': typeof AppPacientesIndexRoute
  '/planos/': typeof AppPlanosIndexRoute
  '/procedimentos/': typeof AppProcedimentosIndexRoute
  '/pacientes/$patientId/relacionamento': typeof AppPacientesPatientIdRelacionamentoRoute
  '/procedimentos/combos/$comboId': typeof AppProcedimentosCombosComboIdRoute
  '/procedimentos/combos/novo': typeof AppProcedimentosCombosNovoRoute
  '/pacientes/$patientId/': typeof AppPacientesPatientIdIndexRoute
  '/pacientes/$patientId/anamneses/$formId': typeof AppPacientesPatientIdAnamnesesFormIdRouteWithChildren
  '/pacientes/$patientId/atendimentos/$attendanceId': typeof AppPacientesPatientIdAtendimentosAttendanceIdRoute
  '/pacientes/$patientId/avulso/$procedureId': typeof AppPacientesPatientIdAvulsoProcedureIdRoute
  '/pacientes/$patientId/novo-atendimento/$itemId': typeof AppPacientesPatientIdNovoAtendimentoItemIdRoute
  '/pacientes/$patientId/anamneses/$formId/respostas': typeof AppPacientesPatientIdAnamnesesFormIdRespostasRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/documentos': typeof AppDocumentosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/assinatura/$token': typeof AssinaturaTokenRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/': typeof AppIndexRoute
  '/contratos/$contractId': typeof AppContratosContractIdRoute
  '/contratos/novo': typeof AppContratosNovoRoute
  '/formularios-anamnese/$anamnesisId': typeof AppFormulariosAnamneseAnamnesisIdRoute
  '/formularios-anamnese/nova': typeof AppFormulariosAnamneseNovaRoute
  '/pacientes/novo': typeof AppPacientesNovoRoute
  '/planos/novo': typeof AppPlanosNovoRoute
  '/procedimentos/$procedureId': typeof AppProcedimentosProcedureIdRoute
  '/procedimentos/novo': typeof AppProcedimentosNovoRoute
  '/contratos': typeof AppContratosIndexRoute
  '/eventos': typeof AppEventosIndexRoute
  '/formularios-anamnese': typeof AppFormulariosAnamneseIndexRoute
  '/pacientes': typeof AppPacientesIndexRoute
  '/planos': typeof AppPlanosIndexRoute
  '/procedimentos': typeof AppProcedimentosIndexRoute
  '/pacientes/$patientId/relacionamento': typeof AppPacientesPatientIdRelacionamentoRoute
  '/procedimentos/combos/$comboId': typeof AppProcedimentosCombosComboIdRoute
  '/procedimentos/combos/novo': typeof AppProcedimentosCombosNovoRoute
  '/pacientes/$patientId': typeof AppPacientesPatientIdIndexRoute
  '/pacientes/$patientId/anamneses/$formId': typeof AppPacientesPatientIdAnamnesesFormIdRouteWithChildren
  '/pacientes/$patientId/atendimentos/$attendanceId': typeof AppPacientesPatientIdAtendimentosAttendanceIdRoute
  '/pacientes/$patientId/avulso/$procedureId': typeof AppPacientesPatientIdAvulsoProcedureIdRoute
  '/pacientes/$patientId/novo-atendimento/$itemId': typeof AppPacientesPatientIdNovoAtendimentoItemIdRoute
  '/pacientes/$patientId/anamneses/$formId/respostas': typeof AppPacientesPatientIdAnamnesesFormIdRespostasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/assinatura/$token': typeof AssinaturaTokenRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/contratos/$contractId': typeof AppContratosContractIdRoute
  '/_app/contratos/novo': typeof AppContratosNovoRoute
  '/_app/formularios-anamnese/$anamnesisId': typeof AppFormulariosAnamneseAnamnesisIdRoute
  '/_app/formularios-anamnese/nova': typeof AppFormulariosAnamneseNovaRoute
  '/_app/pacientes/novo': typeof AppPacientesNovoRoute
  '/_app/planos/novo': typeof AppPlanosNovoRoute
  '/_app/procedimentos/$procedureId': typeof AppProcedimentosProcedureIdRoute
  '/_app/procedimentos/novo': typeof AppProcedimentosNovoRoute
  '/_app/contratos/': typeof AppContratosIndexRoute
  '/_app/eventos/': typeof AppEventosIndexRoute
  '/_app/formularios-anamnese/': typeof AppFormulariosAnamneseIndexRoute
  '/_app/pacientes/': typeof AppPacientesIndexRoute
  '/_app/planos/': typeof AppPlanosIndexRoute
  '/_app/procedimentos/': typeof AppProcedimentosIndexRoute
  '/_app/pacientes/$patientId/relacionamento': typeof AppPacientesPatientIdRelacionamentoRoute
  '/_app/procedimentos/combos/$comboId': typeof AppProcedimentosCombosComboIdRoute
  '/_app/procedimentos/combos/novo': typeof AppProcedimentosCombosNovoRoute
  '/_app/pacientes/$patientId/': typeof AppPacientesPatientIdIndexRoute
  '/_app/pacientes/$patientId/anamneses/$formId': typeof AppPacientesPatientIdAnamnesesFormIdRouteWithChildren
  '/_app/pacientes/$patientId/atendimentos/$attendanceId': typeof AppPacientesPatientIdAtendimentosAttendanceIdRoute
  '/_app/pacientes/$patientId/avulso/$procedureId': typeof AppPacientesPatientIdAvulsoProcedureIdRoute
  '/_app/pacientes/$patientId/novo-atendimento/$itemId': typeof AppPacientesPatientIdNovoAtendimentoItemIdRoute
  '/_app/pacientes/$patientId/anamneses/$formId/respostas': typeof AppPacientesPatientIdAnamnesesFormIdRespostasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/configuracoes'
    | '/documentos'
    | '/financeiro'
    | '/assinatura/$token'
    | '/formulario/$token'
    | '/contratos/$contractId'
    | '/contratos/novo'
    | '/formularios-anamnese/$anamnesisId'
    | '/formularios-anamnese/nova'
    | '/pacientes/novo'
    | '/planos/novo'
    | '/procedimentos/$procedureId'
    | '/procedimentos/novo'
    | '/contratos/'
    | '/eventos/'
    | '/formularios-anamnese/'
    | '/pacientes/'
    | '/planos/'
    | '/procedimentos/'
    | '/pacientes/$patientId/relacionamento'
    | '/procedimentos/combos/$comboId'
    | '/procedimentos/combos/novo'
    | '/pacientes/$patientId/'
    | '/pacientes/$patientId/anamneses/$formId'
    | '/pacientes/$patientId/atendimentos/$attendanceId'
    | '/pacientes/$patientId/avulso/$procedureId'
    | '/pacientes/$patientId/novo-atendimento/$itemId'
    | '/pacientes/$patientId/anamneses/$formId/respostas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agenda'
    | '/configuracoes'
    | '/documentos'
    | '/financeiro'
    | '/assinatura/$token'
    | '/formulario/$token'
    | '/'
    | '/contratos/$contractId'
    | '/contratos/novo'
    | '/formularios-anamnese/$anamnesisId'
    | '/formularios-anamnese/nova'
    | '/pacientes/novo'
    | '/planos/novo'
    | '/procedimentos/$procedureId'
    | '/procedimentos/novo'
    | '/contratos'
    | '/eventos'
    | '/formularios-anamnese'
    | '/pacientes'
    | '/planos'
    | '/procedimentos'
    | '/pacientes/$patientId/relacionamento'
    | '/procedimentos/combos/$comboId'
    | '/procedimentos/combos/novo'
    | '/pacientes/$patientId'
    | '/pacientes/$patientId/anamneses/$formId'
    | '/pacientes/$patientId/atendimentos/$attendanceId'
    | '/pacientes/$patientId/avulso/$procedureId'
    | '/pacientes/$patientId/novo-atendimento/$itemId'
    | '/pacientes/$patientId/anamneses/$formId/respostas'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/configuracoes'
    | '/_app/documentos'
    | '/_app/financeiro'
    | '/assinatura/$token'
    | '/formulario/$token'
    | '/_app/'
    | '/_app/contratos/$contractId'
    | '/_app/contratos/novo'
    | '/_app/formularios-anamnese/$anamnesisId'
    | '/_app/formularios-anamnese/nova'
    | '/_app/pacientes/novo'
    | '/_app/planos/novo'
    | '/_app/procedimentos/$procedureId'
    | '/_app/procedimentos/novo'
    | '/_app/contratos/'
    | '/_app/eventos/'
    | '/_app/formularios-anamnese/'
    | '/_app/pacientes/'
    | '/_app/planos/'
    | '/_app/procedimentos/'
    | '/_app/pacientes/$patientId/relacionamento'
    | '/_app/procedimentos/combos/$comboId'
    | '/_app/procedimentos/combos/novo'
    | '/_app/pacientes/$patientId/'
    | '/_app/pacientes/$patientId/anamneses/$formId'
    | '/_app/pacientes/$patientId/atendimentos/$attendanceId'
    | '/_app/pacientes/$patientId/avulso/$procedureId'
    | '/_app/pacientes/$patientId/novo-atendimento/$itemId'
    | '/_app/pacientes/$patientId/anamneses/$formId/respostas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AssinaturaTokenRoute: typeof AssinaturaTokenRoute
  FormularioTokenRoute: typeof FormularioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/assinatura/$token': {
      id: '/assinatura/$token'
      path: '/assinatura/$token'
      fullPath: '/assinatura/$token'
      preLoaderRoute: typeof AssinaturaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario/$token': {
      id: '/formulario/$token'
      path: '/formulario/$token'
      fullPath: '/formulario/$token'
      preLoaderRoute: typeof FormularioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contratos/': {
      id: '/_app/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AppContratosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos/$contractId': {
      id: '/_app/contratos/$contractId'
      path: '/contratos/$contractId'
      fullPath: '/contratos/$contractId'
      preLoaderRoute: typeof AppContratosContractIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos/novo': {
      id: '/_app/contratos/novo'
      path: '/contratos/novo'
      fullPath: '/contratos/novo'
      preLoaderRoute: typeof AppContratosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos/': {
      id: '/_app/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AppEventosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formularios-anamnese/': {
      id: '/_app/formularios-anamnese/'
      path: '/formularios-anamnese'
      fullPath: '/formularios-anamnese/'
      preLoaderRoute: typeof AppFormulariosAnamneseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formularios-anamnese/$anamnesisId': {
      id: '/_app/formularios-anamnese/$anamnesisId'
      path: '/formularios-anamnese/$anamnesisId'
      fullPath: '/formularios-anamnese/$anamnesisId'
      preLoaderRoute: typeof AppFormulariosAnamneseAnamnesisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formularios-anamnese/nova': {
      id: '/_app/formularios-anamnese/nova'
      path: '/formularios-anamnese/nova'
      fullPath: '/formularios-anamnese/nova'
      preLoaderRoute: typeof AppFormulariosAnamneseNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/': {
      id: '/_app/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/novo': {
      id: '/_app/pacientes/novo'
      path: '/pacientes/novo'
      fullPath: '/pacientes/novo'
      preLoaderRoute: typeof AppPacientesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos/': {
      id: '/_app/planos/'
      path: '/planos'
      fullPath: '/planos/'
      preLoaderRoute: typeof AppPlanosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos/novo': {
      id: '/_app/planos/novo'
      path: '/planos/novo'
      fullPath: '/planos/novo'
      preLoaderRoute: typeof AppPlanosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procedimentos/': {
      id: '/_app/procedimentos/'
      path: '/procedimentos'
      fullPath: '/procedimentos/'
      preLoaderRoute: typeof AppProcedimentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procedimentos/$procedureId': {
      id: '/_app/procedimentos/$procedureId'
      path: '/procedimentos/$procedureId'
      fullPath: '/procedimentos/$procedureId'
      preLoaderRoute: typeof AppProcedimentosProcedureIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procedimentos/novo': {
      id: '/_app/procedimentos/novo'
      path: '/procedimentos/novo'
      fullPath: '/procedimentos/novo'
      preLoaderRoute: typeof AppProcedimentosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$patientId/': {
      id: '/_app/pacientes/$patientId/'
      path: '/pacientes/$patientId'
      fullPath: '/pacientes/$patientId/'
      preLoaderRoute: typeof AppPacientesPatientIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$patientId/relacionamento': {
      id: '/_app/pacientes/$patientId/relacionamento'
      path: '/pacientes/$patientId/relacionamento'
      fullPath: '/pacientes/$patientId/relacionamento'
      preLoaderRoute: typeof AppPacientesPatientIdRelacionamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procedimentos/combos/$comboId': {
      id: '/_app/procedimentos/combos/$comboId'
      path: '/procedimentos/combos/$comboId'
      fullPath: '/procedimentos/combos/$comboId'
      preLoaderRoute: typeof AppProcedimentosCombosComboIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procedimentos/combos/novo': {
      id: '/_app/procedimentos/combos/novo'
      path: '/procedimentos/combos/novo'
      fullPath: '/procedimentos/combos/novo'
      preLoaderRoute: typeof AppProcedimentosCombosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$patientId/anamneses/$formId': {
      id: '/_app/pacientes/$patientId/anamneses/$formId'
      path: '/pacientes/$patientId/anamneses/$formId'
      fullPath: '/pacientes/$patientId/anamneses/$formId'
      preLoaderRoute: typeof AppPacientesPatientIdAnamnesesFormIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$patientId/atendimentos/$attendanceId': {
      id: '/_app/pacientes/$patientId/atendimentos/$attendanceId'
      path: '/pacientes/$patientId/atendimentos/$attendanceId'
      fullPath: '/pacientes/$patientId/atendimentos/$attendanceId'
      preLoaderRoute: typeof AppPacientesPatientIdAtendimentosAttendanceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$patientId/avulso/$procedureId': {
      id: '/_app/pacientes/$patientId/avulso/$procedureId'
      path: '/pacientes/$patientId/avulso/$procedureId'
      fullPath: '/pacientes/$patientId/avulso/$procedureId'
      preLoaderRoute: typeof AppPacientesPatientIdAvulsoProcedureIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$patientId/novo-atendimento/$itemId': {
      id: '/_app/pacientes/$patientId/novo-atendimento/$itemId'
      path: '/pacientes/$patientId/novo-atendimento/$itemId'
      fullPath: '/pacientes/$patientId/novo-atendimento/$itemId'
      preLoaderRoute: typeof AppPacientesPatientIdNovoAtendimentoItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$patientId/anamneses/$formId/respostas': {
      id: '/_app/pacientes/$patientId/anamneses/$formId/respostas'
      path: '/respostas'
      fullPath: '/pacientes/$patientId/anamneses/$formId/respostas'
      preLoaderRoute: typeof AppPacientesPatientIdAnamnesesFormIdRespostasRouteImport
      parentRoute: typeof AppPacientesPatientIdAnamnesesFormIdRoute
    }
  }
}

interface AppPacientesPatientIdAnamnesesFormIdRouteChildren {
  AppPacientesPatientIdAnamnesesFormIdRespostasRoute: typeof AppPacientesPatientIdAnamnesesFormIdRespostasRoute
}

const AppPacientesPatientIdAnamnesesFormIdRouteChildren: AppPacientesPatientIdAnamnesesFormIdRouteChildren =
  {
    AppPacientesPatientIdAnamnesesFormIdRespostasRoute:
      AppPacientesPatientIdAnamnesesFormIdRespostasRoute,
  }

const AppPacientesPatientIdAnamnesesFormIdRouteWithChildren =
  AppPacientesPatientIdAnamnesesFormIdRoute._addFileChildren(
    AppPacientesPatientIdAnamnesesFormIdRouteChildren,
  )

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContratosContractIdRoute: typeof AppContratosContractIdRoute
  AppContratosNovoRoute: typeof AppContratosNovoRoute
  AppFormulariosAnamneseAnamnesisIdRoute: typeof AppFormulariosAnamneseAnamnesisIdRoute
  AppFormulariosAnamneseNovaRoute: typeof AppFormulariosAnamneseNovaRoute
  AppPacientesNovoRoute: typeof AppPacientesNovoRoute
  AppPlanosNovoRoute: typeof AppPlanosNovoRoute
  AppProcedimentosProcedureIdRoute: typeof AppProcedimentosProcedureIdRoute
  AppProcedimentosNovoRoute: typeof AppProcedimentosNovoRoute
  AppContratosIndexRoute: typeof AppContratosIndexRoute
  AppEventosIndexRoute: typeof AppEventosIndexRoute
  AppFormulariosAnamneseIndexRoute: typeof AppFormulariosAnamneseIndexRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
  AppPlanosIndexRoute: typeof AppPlanosIndexRoute
  AppProcedimentosIndexRoute: typeof AppProcedimentosIndexRoute
  AppPacientesPatientIdRelacionamentoRoute: typeof AppPacientesPatientIdRelacionamentoRoute
  AppProcedimentosCombosComboIdRoute: typeof AppProcedimentosCombosComboIdRoute
  AppProcedimentosCombosNovoRoute: typeof AppProcedimentosCombosNovoRoute
  AppPacientesPatientIdIndexRoute: typeof AppPacientesPatientIdIndexRoute
  AppPacientesPatientIdAnamnesesFormIdRoute: typeof AppPacientesPatientIdAnamnesesFormIdRouteWithChildren
  AppPacientesPatientIdAtendimentosAttendanceIdRoute: typeof AppPacientesPatientIdAtendimentosAttendanceIdRoute
  AppPacientesPatientIdAvulsoProcedureIdRoute: typeof AppPacientesPatientIdAvulsoProcedureIdRoute
  AppPacientesPatientIdNovoAtendimentoItemIdRoute: typeof AppPacientesPatientIdNovoAtendimentoItemIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppIndexRoute: AppIndexRoute,
  AppContratosContractIdRoute: AppContratosContractIdRoute,
  AppContratosNovoRoute: AppContratosNovoRoute,
  AppFormulariosAnamneseAnamnesisIdRoute:
    AppFormulariosAnamneseAnamnesisIdRoute,
  AppFormulariosAnamneseNovaRoute: AppFormulariosAnamneseNovaRoute,
  AppPacientesNovoRoute: AppPacientesNovoRoute,
  AppPlanosNovoRoute: AppPlanosNovoRoute,
  AppProcedimentosProcedureIdRoute: AppProcedimentosProcedureIdRoute,
  AppProcedimentosNovoRoute: AppProcedimentosNovoRoute,
  AppContratosIndexRoute: AppContratosIndexRoute,
  AppEventosIndexRoute: AppEventosIndexRoute,
  AppFormulariosAnamneseIndexRoute: AppFormulariosAnamneseIndexRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
  AppPlanosIndexRoute: AppPlanosIndexRoute,
  AppProcedimentosIndexRoute: AppProcedimentosIndexRoute,
  AppPacientesPatientIdRelacionamentoRoute:
    AppPacientesPatientIdRelacionamentoRoute,
  AppProcedimentosCombosComboIdRoute: AppProcedimentosCombosComboIdRoute,
  AppProcedimentosCombosNovoRoute: AppProcedimentosCombosNovoRoute,
  AppPacientesPatientIdIndexRoute: AppPacientesPatientIdIndexRoute,
  AppPacientesPatientIdAnamnesesFormIdRoute:
    AppPacientesPatientIdAnamnesesFormIdRouteWithChildren,
  AppPacientesPatientIdAtendimentosAttendanceIdRoute:
    AppPacientesPatientIdAtendimentosAttendanceIdRoute,
  AppPacientesPatientIdAvulsoProcedureIdRoute:
    AppPacientesPatientIdAvulsoProcedureIdRoute,
  AppPacientesPatientIdNovoAtendimentoItemIdRoute:
    AppPacientesPatientIdNovoAtendimentoItemIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AssinaturaTokenRoute: AssinaturaTokenRoute,
  FormularioTokenRoute: FormularioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
