import { afterAll, beforeAll, describe, expect, it } from 'bun:test';
import { and, eq, sql } from 'drizzle-orm';
import { app } from './app';
import { appliedAnamneses, appliedDocuments, appliedAnamnesisNotes, appliedDocumentRevisions, anamneses, anamnesisVersions, closeDatabase, combos, comboItems, contracts, contractVersions, documentCleanupJobs, followupContracts, followupItems, followupSnapshots, followups, getDatabase, migrateDatabase, patients, procedures, tenants, pdfUploadIntents } from '@clinicare/db';

import { assertSafeIntegrationDatabase, cleanupIntegrationClinics, integration, integrationHeaders, provisionIntegrationClinic, type IntegrationClinic } from './integration-support';
import { storage } from './storage';
let clinic: IntegrationClinic;
let otherClinic: IntegrationClinic;
let tenantId: string;
let otherTenantId: string;
const headers = (tenant: string) => integrationHeaders(tenant);
const request = (tenant: string, path: string, init: RequestInit = {}) => app.request(path, { ...init, headers: { ...headers(tenant), ...(init.headers ?? {}) } });
const post = (tenant: string, path: string, body: unknown) => request(tenant, path, { method: 'POST', body: JSON.stringify(body) });

integration('clinical relational workflows', () => {
  beforeAll(async () => {
    assertSafeIntegrationDatabase(); await migrateDatabase(); clinic = await provisionIntegrationClinic(app, 'clinical'); otherClinic = await provisionIntegrationClinic(app, 'clinical-other'); tenantId = clinic.tenantId; otherTenantId = otherClinic.tenantId; });
  afterAll(async () => { const db = getDatabase(); await db.delete(documentCleanupJobs).where(eq(documentCleanupJobs.tenantId, tenantId)); await db.delete(documentCleanupJobs).where(eq(documentCleanupJobs.tenantId, otherTenantId)); await db.delete(pdfUploadIntents).where(eq(pdfUploadIntents.tenantId, tenantId)); await db.delete(appliedDocuments).where(eq(appliedDocuments.tenantId, tenantId)); await db.delete(pdfUploadIntents).where(eq(pdfUploadIntents.tenantId, otherTenantId)); await db.delete(appliedDocuments).where(eq(appliedDocuments.tenantId, otherTenantId)); await db.execute(sql`alter table applied_anamnesis_notes disable trigger applied_anamnesis_notes_append_only`); await db.execute(sql`delete from applied_anamnesis_notes where tenant_id = ${tenantId}`); await db.execute(sql`alter table applied_anamnesis_notes enable trigger applied_anamnesis_notes_append_only`); await db.delete(appliedAnamneses).where(eq(appliedAnamneses.tenantId, tenantId)); await db.delete(followupContracts).where(eq(followupContracts.tenantId, tenantId)); await db.delete(contractVersions).where(eq(contractVersions.tenantId, tenantId)); await db.delete(contracts).where(eq(contracts.tenantId, tenantId)); await db.delete(followupSnapshots).where(eq(followupSnapshots.tenantId, tenantId)); await db.delete(followupItems).where(eq(followupItems.tenantId, tenantId)); await db.delete(followups).where(eq(followups.tenantId, tenantId)); await db.delete(anamnesisVersions).where(eq(anamnesisVersions.tenantId, tenantId)); await db.delete(anamneses).where(eq(anamneses.tenantId, tenantId)); await db.delete(comboItems).where(eq(comboItems.tenantId, tenantId)); await db.delete(combos).where(eq(combos.tenantId, tenantId)); await db.delete(procedures).where(eq(procedures.tenantId, tenantId)); await db.delete(patients).where(eq(patients.tenantId, tenantId)); await cleanupIntegrationClinics([tenantId, otherTenantId]); await closeDatabase(); });

  async function fixture() {
    const db = getDatabase(), patientId = crypto.randomUUID(), procedureId = crypto.randomUUID(), comboId = crypto.randomUUID(), anamnesisId = crypto.randomUUID(), versionId = crypto.randomUUID();
    await db.insert(patients).values({ id: patientId, tenantId, fullName: 'Paciente clínico' });
    await db.insert(procedures).values({ id: procedureId, tenantId, name: 'Procedimento clínico', durationMinutes: 30, priceCents: 100, sessionSchema: { type: 'object', properties: {} } });
    await db.insert(combos).values({ id: comboId, tenantId, name: 'Combo clínico', priceCents: 100 }); await db.insert(comboItems).values({ tenantId, comboId, procedureId, sessions: 1 });
    await db.insert(anamneses).values({ id: anamnesisId, tenantId, title: 'Título original', validityMonths: 3 }); await db.insert(anamnesisVersions).values({ id: versionId, tenantId, anamnesisId, version: 1, schema: { type: 'object', properties: {} } });
    const followup = await (await post(tenantId, '/api/followups', { patientId, offerType: 'combo', offerId: comboId })).json() as any;
    const contractId = crypto.randomUUID();
    await db.insert(contracts).values({ id: contractId, tenantId, title: 'Contrato clínico', kind: 'standard' });
    await db.insert(contractVersions).values({ tenantId, contractId, version: 1, content: 'Contrato', sourceObjectKey: null });
    await db.insert(followupContracts).values({ tenantId, followupId: followup.id, contractId, contractVersion: 1, titleSnapshot: 'Contrato clínico', renderedPdfObjectKey: crypto.randomUUID(), renderedPdfHash: 'a'.repeat(64), renderedPdfSize: 123, renderedPdfContentType: 'application/pdf', required: true });
    const applied = await (await post(tenantId, '/api/patient-anamneses', { patientId, anamnesisId, followupId: followup.id })).json() as any;
    return { patientId, followupId: followup.id, appliedId: applied.id };
  }
  it('encrypts answers, clears draft, snapshots validity, and only accepts one concurrent submission', async () => {
    const f = await fixture(); const link = await (await post(tenantId, '/api/anamnesis-requests', { patientAnamnesisId: f.appliedId })).json() as any; const token = link.url.split('/').at(-1);
    expect((await request(tenantId, `/public/anamnesis/${token}/draft`, { method: 'PUT', body: JSON.stringify({ draft: { a: 1 } }) })).status).toBe(200);
    const responses = await Promise.all([post(tenantId, `/public/anamnesis/${token}/submit`, { answers: { a: 2 } }), post(tenantId, `/public/anamnesis/${token}/submit`, { answers: { a: 3 } })]);
    expect(responses.filter((response) => response.status === 201)).toHaveLength(1); expect(responses.filter((response) => response.status === 409)).toHaveLength(1);
    const row = (await getDatabase().select().from(appliedAnamneses).where(eq(appliedAnamneses.id, f.appliedId)))[0]!; expect(row.answersCiphertext).toBeTruthy(); expect(row.draftCiphertext).toBeNull(); expect(row.validityMonths).toBe(3); expect(row.validUntil!.getMonth()).toBe((row.submittedAt!.getMonth() + 3) % 12);
    expect((await request(tenantId, `/api/patient-anamneses/${f.appliedId}`)).json()).resolves.toMatchObject({ answers: { a: expect.any(Number) }, title: 'Título original' });
    expect((await post(tenantId, `/api/anamnesis-responses/${f.appliedId}/notes`, { content: 'nota' })).status).toBe(201);
  });
  it('isolates clinical records and rejects notes before answer', async () => { const f = await fixture(); expect((await request(otherTenantId, `/api/patient-anamneses/${f.appliedId}`)).status).toBe(404); expect((await post(tenantId, `/api/anamnesis-responses/${f.appliedId}/notes`, { content: 'prematura' })).status).toBe(404); });
  it('rejects applied-document uploads without a valid rendered PDF hash and size', async () => { const f = await fixture(); const contract = (await getDatabase().select().from(followupContracts).where(eq(followupContracts.followupId, f.followupId)))[0]!; const response = await post(tenantId, `/api/followup-contracts/${contract.id}/documents/presign`, { contentType: 'application/pdf', contentHash: 'sha256:test', size: 123 }); expect(response.status).toBe(400); });
  it('materializes only the immutable contract PDF and rejects client-selected metadata', async () => { const f = await fixture(); const contract = (await getDatabase().select().from(followupContracts).where(eq(followupContracts.followupId, f.followupId)))[0]!; const rejected = await post(tenantId, `/api/followup-contracts/${contract.id}/documents/presign`, { contentType: 'application/pdf', contentHash: 'b'.repeat(64), size: 999 }); expect(rejected.status).toBe(400); if (!storage) { const materialized = await post(tenantId, `/api/followup-contracts/${contract.id}/documents`, { uploadIntentId: crypto.randomUUID(), contentType: 'application/pdf', contentHash: 'b'.repeat(64), size: 999 }); expect(materialized.status).toBe(503); } });
  it('deletes a document and all immutable revisions through the aggregate boundary', async () => { const db = getDatabase(); const f = await fixture(); const contract = (await db.select().from(followupContracts).where(eq(followupContracts.followupId, f.followupId)))[0]!; const documentId = crypto.randomUUID(); const revisionId = crypto.randomUUID(); await db.execute(sql`select set_config('app.constructing_applied_document', 'on', true)`); await db.insert(appliedDocuments).values({ id: documentId, tenantId, followupContractId: contract.id, originalObjectKey: crypto.randomUUID(), originalHash: 'a'.repeat(64), originalSize: 123 }); await db.insert(appliedDocumentRevisions).values({ id: revisionId, tenantId, documentId, version: 1, objectKey: crypto.randomUUID(), contentHash: 'a'.repeat(64), contentSize: 123 }); await db.execute(sql`select set_config('app.constructing_applied_document', 'on', true)`); await db.update(appliedDocuments).set({ currentRevisionId: revisionId }).where(and(eq(appliedDocuments.tenantId, tenantId), eq(appliedDocuments.id, documentId))); await db.execute(sql`select set_config('app.constructing_applied_document', 'off', true)`); if (!storage) { const response = await request(tenantId, `/api/applied-documents/${documentId}`, { method: 'DELETE' }); expect(response.status).toBe(503); expect(await db.select().from(appliedDocuments).where(eq(appliedDocuments.id, documentId))).toHaveLength(0); expect(await db.select().from(appliedDocumentRevisions).where(eq(appliedDocumentRevisions.documentId, documentId))).toHaveLength(0); expect(await db.select().from(documentCleanupJobs).where(eq(documentCleanupJobs.documentId, documentId))).toMatchObject([{ status: 'failed', attempts: 1 }]); } else { const response = await request(tenantId, `/api/applied-documents/${documentId}`, { method: 'DELETE' }); expect(response.status).toBe(200); expect(await db.select().from(appliedDocumentRevisions).where(eq(appliedDocumentRevisions.documentId, documentId))).toHaveLength(0); expect(await db.select().from(documentCleanupJobs).where(eq(documentCleanupJobs.documentId, documentId))).toMatchObject([{ status: 'completed' }]); } });
});
